-- afarma.produtocrawler definition

-- Drop table

-- DROP TABLE afarma.produtocrawler;

CREATE TABLE afarma.produto_afarma (
	id varchar(36) NOT NULL DEFAULT uuid_generate_v4(),
	ean varchar(10240) NULL,
	nome varchar(10240) NULL,
	valor float8 not null,
	photo_id varchar(36) NULL,
	ean_similar varchar(10240) NULL,
	active boolean not null default true,
	produto_tsv tsvector NULL,
	CONSTRAINT produtoafarma_pkey PRIMARY KEY (id),
	CONSTRAINT produtoafarma_unique UNIQUE (ean)
);



insert into afarma.produto_afarma (nome, valor) values ('AAS - ACIDO ACETILSALICILICO 100MG C/20','4.51');
insert into afarma.produto_afarma (nome, valor) values ('AAS PROTECT 100MG C/30','15.87');
insert into afarma.produto_afarma (nome, valor) values ('ABSORVENTE GERIÁTRICO C/20','12.67');
insert into afarma.produto_afarma (nome, valor) values ('ACCU-CHECK FASTCLIX 102 LANCETAS','79.9');
insert into afarma.produto_afarma (nome, valor) values ('ACETILCISTEINA 100MG (ENVELOPE) C/16','19.78');
insert into afarma.produto_afarma (nome, valor) values ('ACETILCISTEINA 200MG (ENVELOPE) C/16','15.99');
insert into afarma.produto_afarma (nome, valor) values ('ACETILCISTEINA 600MG (ENVELOPE) C/16','26.03');
insert into afarma.produto_afarma (nome, valor) values ('ACEVITON ARGININA 16CPR','17.26');
insert into afarma.produto_afarma (nome, valor) values ('ÁCIDO ASCÓRBICO 1G C/10','7.28');
insert into afarma.produto_afarma (nome, valor) values ('ACIDO FÓLICO 5MG C/20','3.99');
insert into afarma.produto_afarma (nome, valor) values ('ACIDO HIALURONICO POMADA','26.97');
insert into afarma.produto_afarma (nome, valor) values ('ACTONEL CHRONOS 35MG C/4','162.29');
insert into afarma.produto_afarma (nome, valor) values ('AKINETON 2MG C/80','35.99');
insert into afarma.produto_afarma (nome, valor) values ('ALCACHOFRA  100CPR','49.95');
insert into afarma.produto_afarma (nome, valor) values ('ALDACTONE 25MG C/30','27.38');
insert into afarma.produto_afarma (nome, valor) values ('ALENDRONATO DE SODIO 70MG C/4 ','5.99');
insert into afarma.produto_afarma (nome, valor) values ('ALGINAC 1.000 - 30 CP','53.35');
insert into afarma.produto_afarma (nome, valor) values ('ALOPURINOL 100MG C/30','6.91');
insert into afarma.produto_afarma (nome, valor) values ('ALPRAZOLAM 0,25MG 30CPR','5.79');
insert into afarma.produto_afarma (nome, valor) values ('ALPRAZOLAM 0,5MG C/30','6.38');
insert into afarma.produto_afarma (nome, valor) values ('ALPRAZOLAM 1,0 MG C/30','9.5');
insert into afarma.produto_afarma (nome, valor) values ('ALPRAZOLAM 2,0 MG C/30','19.99');
insert into afarma.produto_afarma (nome, valor) values ('ALTA D 15000UI','39.49');
insert into afarma.produto_afarma (nome, valor) values ('AMBROXOL XAROPE 120ML','8.53');
insert into afarma.produto_afarma (nome, valor) values ('AMINOFILINA 100MG','2.93');
insert into afarma.produto_afarma (nome, valor) values ('AMIODARONA 100MG C/30','13.54');
insert into afarma.produto_afarma (nome, valor) values ('AMIODARONA 200MG C/30','23.39');
insert into afarma.produto_afarma (nome, valor) values ('AMITRIPTILINA 25MG C/30','9.26');
insert into afarma.produto_afarma (nome, valor) values ('AMOXICILINA + CLAV  875MG 14CP','41.4');
insert into afarma.produto_afarma (nome, valor) values ('AMOXICILINA 500MG C/21','26.24');
insert into afarma.produto_afarma (nome, valor) values ('AMPLICTIL 100MG C/20','10.07');
insert into afarma.produto_afarma (nome, valor) values ('AMPLICTIL 25MG C/20','7.28');
insert into afarma.produto_afarma (nome, valor) values ('AMPLICTIL 4% 20ML GTS','9.19');
insert into afarma.produto_afarma (nome, valor) values ('ANLODIPINO 10MG C/30','8.14');
insert into afarma.produto_afarma (nome, valor) values ('ANLODIPINO 5MG C/30','5.99');
insert into afarma.produto_afarma (nome, valor) values ('APRESOLINA 25MG C/20','7.48');
insert into afarma.produto_afarma (nome, valor) values ('APRESOLINA 50MG C/20','9.27');
insert into afarma.produto_afarma (nome, valor) values ('ARCALION C/ 60','126.89');
insert into afarma.produto_afarma (nome, valor) values ('ARIPIPRAZOL 10MG C/30 COMP','91.12');
insert into afarma.produto_afarma (nome, valor) values ('ARPADOL 400MG  C/60 ','156.89');
insert into afarma.produto_afarma (nome, valor) values ('ARTRODAR 50MG 30CPS','169.99');
insert into afarma.produto_afarma (nome, valor) values ('ARTROGEN DUO 30 SACHES C/ 11 G','162.44');
insert into afarma.produto_afarma (nome, valor) values ('ARTROLIVE 500 + 400 30CAPS','82.96');
insert into afarma.produto_afarma (nome, valor) values ('ASPIRINA PREVENT 100MG C/30','16.89');
insert into afarma.produto_afarma (nome, valor) values ('ATACAND HCT 16/125MG 30CPR','123.79');
insert into afarma.produto_afarma (nome, valor) values ('ATADURA CREPE 20CM','4.99');
insert into afarma.produto_afarma (nome, valor) values ('ATENOLOL 25MG C/30','2.99');
insert into afarma.produto_afarma (nome, valor) values ('ATENOLOL 50MG C/30','5.99');
insert into afarma.produto_afarma (nome, valor) values ('ATENSINA 0,100MG 30CPR','6.79');
insert into afarma.produto_afarma (nome, valor) values ('ATENSINA 0,200MG 30CPR','10.89');
insert into afarma.produto_afarma (nome, valor) values ('ATIP XR 50 C/30','105.43');
insert into afarma.produto_afarma (nome, valor) values ('ATORVASTATINA CALCICA 10MG C/30','13.12');
insert into afarma.produto_afarma (nome, valor) values ('ATORVASTATINA CALCICA 20MG C/30','19.55');
insert into afarma.produto_afarma (nome, valor) values ('ATROPINA 1% SOL OFT FR C/5ML','10.29');
insert into afarma.produto_afarma (nome, valor) values ('ATROVENT N','29.82');
insert into afarma.produto_afarma (nome, valor) values ('AXETIL CEFUROXIMA 250MG C/10','51.72');
insert into afarma.produto_afarma (nome, valor) values ('AZITROMICINA  500MG 5CPR','16.99');
insert into afarma.produto_afarma (nome, valor) values ('AZITROMICINA 1G C/1','18.9');
insert into afarma.produto_afarma (nome, valor) values ('AZITROMICINA 600MG SUS PL 15ML','21.39');
insert into afarma.produto_afarma (nome, valor) values ('AZITROMICINA 900MG SUS PL 22,5ML','25.3');
insert into afarma.produto_afarma (nome, valor) values ('AZOPT 5ML','63.14');
insert into afarma.produto_afarma (nome, valor) values ('BABYMED 46G','5.99');
insert into afarma.produto_afarma (nome, valor) values ('BACLOFEN 10MG C/20','6.39');
insert into afarma.produto_afarma (nome, valor) values ('BAMIFIX 300 MG C/20','29.49');
insert into afarma.produto_afarma (nome, valor) values ('BECLOMETASONA 250MG 200 DOSES','37.39');
insert into afarma.produto_afarma (nome, valor) values ('BENEUN 300MG 30CPR','16.19');
insert into afarma.produto_afarma (nome, valor) values ('BEROTEC AEROSSOL 100MCG AE 10ML','23.01');
insert into afarma.produto_afarma (nome, valor) values ('BETAISTINA 16MG 30CPR','12.99');
insert into afarma.produto_afarma (nome, valor) values ('BETAISTINA 24MG 30CPR','18.9');
insert into afarma.produto_afarma (nome, valor) values ('BETRAT 42CPR','77.66');
insert into afarma.produto_afarma (nome, valor) values ('BIFILAC C/30 - LACTOBACILOS','89.31');
insert into afarma.produto_afarma (nome, valor) values ('BIMATOPROSTA + MAL TIMOLOL – 3MG','104.98');
insert into afarma.produto_afarma (nome, valor) values ('BIO-C 1G 10CPR EFERV','9.86');
insert into afarma.produto_afarma (nome, valor) values ('BIPERIDENO 2MG','28.97');
insert into afarma.produto_afarma (nome, valor) values ('BISACORDIL 5MG','4.02');
insert into afarma.produto_afarma (nome, valor) values ('BISOPROLOL 2,5MG 30CPR','31.99');
insert into afarma.produto_afarma (nome, valor) values ('BISOPROLOL 5MG C/30 COMP','45.69');
insert into afarma.produto_afarma (nome, valor) values ('BISSULFATO DE CLOPIDOGREL 75MG  C/28','19.5');
insert into afarma.produto_afarma (nome, valor) values ('BRASART HCT 160 / 12,6 C/30','62.8');
insert into afarma.produto_afarma (nome, valor) values ('BRIMONIDINA  0,2% 5ML','25.78');
insert into afarma.produto_afarma (nome, valor) values ('BROMETO IPRATROPIO SOL 20ML ','4.99');
insert into afarma.produto_afarma (nome, valor) values ('BROMOPRIDA 10MG C/20','9.97');
insert into afarma.produto_afarma (nome, valor) values ('BROMOPRIDA 4MG GOTAS','8.52');
insert into afarma.produto_afarma (nome, valor) values ('BUCLINA 25MG C/30','14.95');
insert into afarma.produto_afarma (nome, valor) values ('BUDESONIDA 0,25MG/ML','38.79');
insert into afarma.produto_afarma (nome, valor) values ('BUDESONIDA 50 MCG','29.49');
insert into afarma.produto_afarma (nome, valor) values ('BUSCOPAM COMPOSTO 20ML','14.24');
insert into afarma.produto_afarma (nome, valor) values ('CALCIODEX 625MG + D3 C/90','26');
insert into afarma.produto_afarma (nome, valor) values ('CALCIODEX MDK C/30','37.99');
insert into afarma.produto_afarma (nome, valor) values ('CALCITRAN MDK C/30','51.55');
insert into afarma.produto_afarma (nome, valor) values ('CALCIUM MAXX 600G + D3  C/60CPR','26');
insert into afarma.produto_afarma (nome, valor) values ('CALMAN C/20 COMP.','37.77');
insert into afarma.produto_afarma (nome, valor) values ('CAPTOPRIL 25MG','3.85');
insert into afarma.produto_afarma (nome, valor) values ('CARBAMAZEPINA 200MG 20CPR','9.53');
insert into afarma.produto_afarma (nome, valor) values ('CARBOLITIUM CR 450MG 30CPR','52.49');
insert into afarma.produto_afarma (nome, valor) values ('CARDIZEM SR 90MG C/20','39.97');
insert into afarma.produto_afarma (nome, valor) values ('CARVEDILOL 12.5 MG','13.59');
insert into afarma.produto_afarma (nome, valor) values ('CARVEDILOL 3.125 MG','9.91');
insert into afarma.produto_afarma (nome, valor) values ('CARVEDILOL 6.250 MG','12.99');
insert into afarma.produto_afarma (nome, valor) values ('CASTANHA DA INDIA 100MG C/30','19.97');
insert into afarma.produto_afarma (nome, valor) values ('CEFALEXINA 500MG C/10','10.99');
insert into afarma.produto_afarma (nome, valor) values ('CENTRUM C/30','49.9');
insert into afarma.produto_afarma (nome, valor) values ('CETOCONAZOL + BETAMETASONA CREME 30G','12.49');
insert into afarma.produto_afarma (nome, valor) values ('CETOCONAZOL 20MG/G CREME','9.91');
insert into afarma.produto_afarma (nome, valor) values ('CETOCONAZOL SHAMPOO ANTI CASPA','12.99');
insert into afarma.produto_afarma (nome, valor) values ('CICLOBENZAPRINA 10MG 30CPR','14.99');
insert into afarma.produto_afarma (nome, valor) values ('CICLOBENZAPRINA 5MG 15CPR','6.39');
insert into afarma.produto_afarma (nome, valor) values ('CILOSTAZOL 100MG C/30','23.29');
insert into afarma.produto_afarma (nome, valor) values ('CILOSTAZOL 50MG 30CPR','12.59');
insert into afarma.produto_afarma (nome, valor) values ('CINARIZINA 25MG C/30','8.12');
insert into afarma.produto_afarma (nome, valor) values ('CINARIZINA 75MG C/30','11.37');
insert into afarma.produto_afarma (nome, valor) values ('CINETOL 2MG C/80 ','28.97');
insert into afarma.produto_afarma (nome, valor) values ('CIPROFIBRATO 100MG C/30','29.43');
insert into afarma.produto_afarma (nome, valor) values ('CIPROFLOXACINO  500MG 14CPR','12.99');
insert into afarma.produto_afarma (nome, valor) values ('CITALOPRAM  20 MG C/30 ','15.99');
insert into afarma.produto_afarma (nome, valor) values ('CITONEURIN 5000 C/20 CPR','51.33');
insert into afarma.produto_afarma (nome, valor) values ('CITONEURIN 5000 C/60 CPR','135.94');
insert into afarma.produto_afarma (nome, valor) values ('CITONEURIN 5000 MCG','13.79');
insert into afarma.produto_afarma (nome, valor) values ('CLENIL HFA 250 MCG','53.19');
insert into afarma.produto_afarma (nome, valor) values ('CLONAZEPAM  2MG C/30','8.25');
insert into afarma.produto_afarma (nome, valor) values ('CLONAZEPAM 0,25MG C/30','5.79');
insert into afarma.produto_afarma (nome, valor) values ('CLONAZEPAM 0,5MG C/30','5.95');
insert into afarma.produto_afarma (nome, valor) values ('CLONAZEPAM 2,5MG SOL','7.65');
insert into afarma.produto_afarma (nome, valor) values ('CLOPIXOL ACUPHASE 50MG 1X1ML','44.79');
insert into afarma.produto_afarma (nome, valor) values ('CLOPIXOL DEPOT 200MG','80.05');
insert into afarma.produto_afarma (nome, valor) values ('CLOZAPINA 100MG','149.97');
insert into afarma.produto_afarma (nome, valor) values ('COBAVITAL 1MG+4MG','29.99');
insert into afarma.produto_afarma (nome, valor) values ('COBAVITAL 30CPR','32.83');
insert into afarma.produto_afarma (nome, valor) values ('CODEÍNA 30MG 30 CAPSULA','38.35');
insert into afarma.produto_afarma (nome, valor) values ('COGNITUS 225MG 60CPR','99.95');
insert into afarma.produto_afarma (nome, valor) values ('COLARTROX 30 SACHÊS 10G','97.99');
insert into afarma.produto_afarma (nome, valor) values ('COLCHICINA - COCICHIMIL 0,5MG C/20 COMP','7.75');
insert into afarma.produto_afarma (nome, valor) values ('COLCHICINA - COCICHIMIL 0,5MG C/30 COMP','11.62');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO  LATANOPROSTA 50MG - ARULATAN 2,5ML','110.99');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO ECOFILM 5MG SOL OFT','17.63');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO FRESH TEARS 0,5%','35.81');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO LACRIFILM 10ML','20.38');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO LACRIFILM 15ML','28.67');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO LACRIMA PLUS 15ML ','23.93');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO LUMIGAN RC 0,01% - 3ML','101.97');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO MALEATO TIMOLOL 0,5 - 5ML','4.89');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO MAXITROL - 5ML','16.99');
insert into afarma.produto_afarma (nome, valor) values ('COLIRIO MOURA BRASIL 20ML','15.11');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO OFTANE C/10ML','39.2');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO OPTIVE 10ML','49.71');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO OTOCIRIAX 5ML','35.23');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO STER MD 1,2 MG/ML - 10 ML','39.99');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO STILL - 5ML ','15.59');
insert into afarma.produto_afarma (nome, valor) values ('COLÍRIO TRAVATAN 0,04MG/ML','34.56');
insert into afarma.produto_afarma (nome, valor) values ('COMBIRON FOLICO C/45','32.55');
insert into afarma.produto_afarma (nome, valor) values ('COMBIRON SOLUÇÃO ORAL 30ML','20.89');
insert into afarma.produto_afarma (nome, valor) values ('COMBODART 30CPS','112.86');
insert into afarma.produto_afarma (nome, valor) values ('COMPLEXO B - GOTAS','7.78');
insert into afarma.produto_afarma (nome, valor) values ('COMPLEXO B 500MG 100CPR','19.8');
insert into afarma.produto_afarma (nome, valor) values ('CONDICIONADOR 350 ML','8.99');
insert into afarma.produto_afarma (nome, valor) values ('CONVIVANCE 900+100MG C 30 CP','97.16');
insert into afarma.produto_afarma (nome, valor) values ('COREGA ULTRA CREME 8,5G','10.38');
insert into afarma.produto_afarma (nome, valor) values ('CORUS 25MG C/30','38.39');
insert into afarma.produto_afarma (nome, valor) values ('COTONETE C/150','4.69');
insert into afarma.produto_afarma (nome, valor) values ('CREME DE BARBEAR NIVEA 65G','8.99');
insert into afarma.produto_afarma (nome, valor) values ('CREME DE PENTEAR SEDA','9.49');
insert into afarma.produto_afarma (nome, valor) values ('CREME DENTAL COLGATE 180G','5.59');
insert into afarma.produto_afarma (nome, valor) values ('CUMARINA + HEPARINA 5MG/50 UI CREME ','56.67');
insert into afarma.produto_afarma (nome, valor) values ('DAFLON FLEX 1000MG 30ENV','136.52');
insert into afarma.produto_afarma (nome, valor) values ('DEPAKENE 500MG C/ 50 ','66.79');
insert into afarma.produto_afarma (nome, valor) values ('DEPAKENE 50MG ML XAROPE 100ML','17.35');
insert into afarma.produto_afarma (nome, valor) values ('DEPAKOTE ER 250ML C/60','91.99');
insert into afarma.produto_afarma (nome, valor) values ('DEPURA 500 UI/GOTA','59.91');
insert into afarma.produto_afarma (nome, valor) values ('DERMAEX 100ML','5.5');
insert into afarma.produto_afarma (nome, valor) values ('DERMAEX 200ML','9.9');
insert into afarma.produto_afarma (nome, valor) values ('DESLORATADINA 5MG C/30','31.44');
insert into afarma.produto_afarma (nome, valor) values ('DESODORANTE AEROSOL 90G','6.99');
insert into afarma.produto_afarma (nome, valor) values ('DESOL 10ML','26.79');
insert into afarma.produto_afarma (nome, valor) values ('DEXADOR 5000 MCG C/20','51.99');
insert into afarma.produto_afarma (nome, valor) values ('DEXAMETASONA 1MG/G CREME','3.28');
insert into afarma.produto_afarma (nome, valor) values ('DEXILANT 30MG 30CAPS','92.6');
insert into afarma.produto_afarma (nome, valor) values ('DIAMOX 250MG 25CPR','16.39');
insert into afarma.produto_afarma (nome, valor) values ('DIAZEPAM 5MG C/30','6.79');
insert into afarma.produto_afarma (nome, valor) values ('DICLOFENACO DE POTÁSSIO 50MG C/20','4.99');
insert into afarma.produto_afarma (nome, valor) values ('DICLOFENACO DIETILAMÔNIO GEL 11,6MG ','9.9');
insert into afarma.produto_afarma (nome, valor) values ('DIGOXINA 0,25MG C/30','5.2');
insert into afarma.produto_afarma (nome, valor) values ('DIOVAN HCT 160 12,5MG 28CPR','104.39');
insert into afarma.produto_afarma (nome, valor) values ('DIPIRONA  SÓDICA 500MG  10CPR','3.99');
insert into afarma.produto_afarma (nome, valor) values ('DIPIRONA 1G 10CPR','11.49');
insert into afarma.produto_afarma (nome, valor) values ('DIPIRONA GTS 20ML','4.85');
insert into afarma.produto_afarma (nome, valor) values ('DIVALCON ER 500MG C/30','64.88');
insert into afarma.produto_afarma (nome, valor) values ('DIVALPROATO DE SODIO  500MG C/20','47.19');
insert into afarma.produto_afarma (nome, valor) values ('DIVALPROATO DE SODIO 250MG 20 COMP','18.98');
insert into afarma.produto_afarma (nome, valor) values ('DOMPERIDONA 10MG C/30','9.91');
insert into afarma.produto_afarma (nome, valor) values ('DONAREN RETARD 150MG 30CPR','136.68');
insert into afarma.produto_afarma (nome, valor) values ('DONEPEZILA 10MG CX 30 COMP ','49.81');
insert into afarma.produto_afarma (nome, valor) values ('DONEPEZILA 5MG C/30','44.05');
insert into afarma.produto_afarma (nome, valor) values ('DORZOLAM OFT 5ML','36.22');
insert into afarma.produto_afarma (nome, valor) values ('DORZOLAMIDA 2% 5ML','34.42');
insert into afarma.produto_afarma (nome, valor) values ('DOXAZOSINA 2MG','9.99');
insert into afarma.produto_afarma (nome, valor) values ('DOXAZOSINA 4MG','25.99');
insert into afarma.produto_afarma (nome, valor) values ('DOZEMAST 1000MG 30CPR','70.87');
insert into afarma.produto_afarma (nome, valor) values ('DRENATAN COLIRIO 0,005% 2,5ML','113.94');
insert into afarma.produto_afarma (nome, valor) values ('DULOXETINA 30MG C/30','44.12');
insert into afarma.produto_afarma (nome, valor) values ('DULOXETINA 60MG C/30','98.12');
insert into afarma.produto_afarma (nome, valor) values ('DUO TRAVATAN BAK FREE COL 2,5ML','146.98');
insert into afarma.produto_afarma (nome, valor) values ('DUOVENT N 10ML','16.24');
insert into afarma.produto_afarma (nome, valor) values ('ECASIL-81  30CPR','12.57');
insert into afarma.produto_afarma (nome, valor) values ('ELIQUIS 5MG C 60COMP','256.99');
insert into afarma.produto_afarma (nome, valor) values ('ENALAPRIL 10MG C/30','3.54');
insert into afarma.produto_afarma (nome, valor) values ('ENALAPRIL 20MG C/30','13.2');
insert into afarma.produto_afarma (nome, valor) values ('ENALAPRIL 5MG C/30','6.56');
insert into afarma.produto_afarma (nome, valor) values ('ENEMED 130ML','14.89');
insert into afarma.produto_afarma (nome, valor) values ('ENVID 30 CAPS','63.23');
insert into afarma.produto_afarma (nome, valor) values ('ENXAGUANTE BUCAL 500 ML','13.99');
insert into afarma.produto_afarma (nome, valor) values ('ESCITALOPRAM 10MG C/30','21.49');
insert into afarma.produto_afarma (nome, valor) values ('ESCITALOPRAM 15MG C/30','38.35');
insert into afarma.produto_afarma (nome, valor) values ('ESCITALOPRAM 20MG C/30','32.8');
insert into afarma.produto_afarma (nome, valor) values ('ESCOVA DENTAL COLGATE','4.79');
insert into afarma.produto_afarma (nome, valor) values ('ESOMEPRAZOL 20MG C/28','53.69');
insert into afarma.produto_afarma (nome, valor) values ('ESOMEPRAZOL 40 MG C/28','92.49');
insert into afarma.produto_afarma (nome, valor) values ('ESPARADRAPO HIPOALERGÊNICO 10X4,5 MISSNER','11.99');
insert into afarma.produto_afarma (nome, valor) values ('ESPARADRAPO IMPERMEÁVEL 10X4,5 MISSNER','10.15');
insert into afarma.produto_afarma (nome, valor) values ('ESPIRONOLACTONA 25MG','10.44');
insert into afarma.produto_afarma (nome, valor) values ('ETNA 50CPS','115.12');
insert into afarma.produto_afarma (nome, valor) values ('EXELON PATCH 5 C/30 ADESIVOS','525.89');
insert into afarma.produto_afarma (nome, valor) values ('FENITOINA SOD 100MG C 30 ','8.99');
insert into afarma.produto_afarma (nome, valor) values ('FENOBARBITAL 100MG 20CPR','5.49');
insert into afarma.produto_afarma (nome, valor) values ('FENOBARBITAL 100MG 30CPR','9.55');
insert into afarma.produto_afarma (nome, valor) values ('FIO DENTAL 100M','5.49');
insert into afarma.produto_afarma (nome, valor) values ('FISIOTON 400MG 30CPR','89.89');
insert into afarma.produto_afarma (nome, valor) values ('FITA MICROPOROSA 10X10CM','10.97');
insert into afarma.produto_afarma (nome, valor) values ('FLEDOID 3MG GEL C/40G','27.67');
insert into afarma.produto_afarma (nome, valor) values ('FLORENT 100MG 12CAPS ','28.66');
insert into afarma.produto_afarma (nome, valor) values ('FLUCONAZOL 150MG 2CAPS ','5.2');
insert into afarma.produto_afarma (nome, valor) values ('FLUOXETINA 20MG 30CP','14.16');
insert into afarma.produto_afarma (nome, valor) values ('FORFIG 100MG 30CPR','78.3');
insert into afarma.produto_afarma (nome, valor) values ('FORFIG 200MG C/60','132.26');
insert into afarma.produto_afarma (nome, valor) values ('FORMOTEROL 12MCG REFIL ','59.21');
insert into afarma.produto_afarma (nome, valor) values ('FRALDA DESCARTÁVEL C/8','14.89');
insert into afarma.produto_afarma (nome, valor) values ('FRISIUM 20MG C/ 20 ','29.93');
insert into afarma.produto_afarma (nome, valor) values ('FUROSEMIDA  40MG 30CPR','5.13');
insert into afarma.produto_afarma (nome, valor) values ('GABAPENTINA 400MG C/30','40.61');
insert into afarma.produto_afarma (nome, valor) values ('GALANTAMINA  16MG 30CPR','112.32');
insert into afarma.produto_afarma (nome, valor) values ('GALANTAMINA  24MG 30CPR','156.02');
insert into afarma.produto_afarma (nome, valor) values ('GALVUS MET 50MG 850MG 56CPR','183.67');
insert into afarma.produto_afarma (nome, valor) values ('GARDENAL 100MG C/20','8.07');
insert into afarma.produto_afarma (nome, valor) values ('GEROVITAL 60CPS SEM','82.03');
insert into afarma.produto_afarma (nome, valor) values ('GINKGO BILOBA 80MG','17.99');
insert into afarma.produto_afarma (nome, valor) values ('GINKOBILOBA 80 MG','19.23');
insert into afarma.produto_afarma (nome, valor) values ('GLAUB 2MG COLÍRIO - 5ML','47.1');
insert into afarma.produto_afarma (nome, valor) values ('GLAUCOTRAT 5MG - 5ML','10.26');
insert into afarma.produto_afarma (nome, valor) values ('GLIBENCLAMIDA 5MG','3.13');
insert into afarma.produto_afarma (nome, valor) values ('GLICLAZIDA 30MG C/30','13.99');
insert into afarma.produto_afarma (nome, valor) values ('GLICLAZIDA 60MG C/30 CPR ','33.91');
insert into afarma.produto_afarma (nome, valor) values ('GLICLAZIDA 60MG C/60 CPR ','52.05');
insert into afarma.produto_afarma (nome, valor) values ('GLIFAGE XR 500MG C/30','6.36');
insert into afarma.produto_afarma (nome, valor) values ('GLIFAGE XR 750 C/30','27.24');
insert into afarma.produto_afarma (nome, valor) values ('GLIFAGE XR 850 C/30','27.99');
insert into afarma.produto_afarma (nome, valor) values ('GLIMEPIRIDA 2MG','9.99');
insert into afarma.produto_afarma (nome, valor) values ('HALDOL 1MG ','6.09');
insert into afarma.produto_afarma (nome, valor) values ('HALDOL 5MG C/20','11.99');
insert into afarma.produto_afarma (nome, valor) values ('HALOPERIDOL 2MG – GOTAS ','13.58');
insert into afarma.produto_afarma (nome, valor) values ('HIDANTAL 25CPS','11.78');
insert into afarma.produto_afarma (nome, valor) values ('HIDRATANTE 500ML','12.99');
insert into afarma.produto_afarma (nome, valor) values ('HIDRION 40/100MG ','26.99');
insert into afarma.produto_afarma (nome, valor) values ('HIDROCLOROTIAZIDA 25MG 30COMP','1.65');
insert into afarma.produto_afarma (nome, valor) values ('HIDROXIZINA 25MG 30CPR','23.33');
insert into afarma.produto_afarma (nome, valor) values ('HUMECTOL-D C/20','13.99');
insert into afarma.produto_afarma (nome, valor) values ('HYABAK 0.15 10ML','57.99');
insert into afarma.produto_afarma (nome, valor) values ('IBANDRONATO DE SODIO 150MG','32.65');
insert into afarma.produto_afarma (nome, valor) values ('IBUPROFENO  100 MG/ML S.ORAL 20ML','7.2');
insert into afarma.produto_afarma (nome, valor) values ('IBUPROFENO 600MG 20CPR ','9.91');
insert into afarma.produto_afarma (nome, valor) values ('INDAPAMIDA 1,5MG 30CPR','10.99');
insert into afarma.produto_afarma (nome, valor) values ('ISORDIL 10MG 30CPR ORAL','9.86');
insert into afarma.produto_afarma (nome, valor) values ('ISOSSORBIDA 20MG C/30','7.15');
insert into afarma.produto_afarma (nome, valor) values ('ISOSSORBIDA 40MG C/30','10.79');
insert into afarma.produto_afarma (nome, valor) values ('JANUVIA 50MG C/28 ','118.04');
insert into afarma.produto_afarma (nome, valor) values ('LABIRIN 24MG C/30','33.2');
insert into afarma.produto_afarma (nome, valor) values ('LABIRIN 8MG C/30','24.8');
insert into afarma.produto_afarma (nome, valor) values ('LACRIBELL COL 15ML','18.39');
insert into afarma.produto_afarma (nome, valor) values ('LACTOLÍNEA  XPE 120ML  (LACTULOSE 667)','11.99');
insert into afarma.produto_afarma (nome, valor) values ('LAMOTRIGINA  25MG 30CPR','14.85');
insert into afarma.produto_afarma (nome, valor) values ('LANCETAS ACCU-CHECK FASTCLIX 102 LANCETS','79.9');
insert into afarma.produto_afarma (nome, valor) values ('LAVITAN 50+ C/60','29.99');
insert into afarma.produto_afarma (nome, valor) values ('LAVITAN COLAGENO TIPO II 30CPR ','61.91');
insert into afarma.produto_afarma (nome, valor) values ('LAVITAN CRANBERRY 30CPR ','39.9');
insert into afarma.produto_afarma (nome, valor) values ('LAVITAN MEMÓRIA C/60','26');
insert into afarma.produto_afarma (nome, valor) values ('LEITE DE ROSAS 100ML','4.45');
insert into afarma.produto_afarma (nome, valor) values ('LENÇO UMEDECIDO ADULTO C/40','10.9');
insert into afarma.produto_afarma (nome, valor) values ('LERCANIDIPINO 10MG 30CPR','56.13');
insert into afarma.produto_afarma (nome, valor) values ('LEVANLODIPINO 2,5MG','59.2');
insert into afarma.produto_afarma (nome, valor) values ('LEVERCTIN 6MG 4CPR (IVERMECTINA)','18.26');
insert into afarma.produto_afarma (nome, valor) values ('LEVOFLOXACINO 500MG C/10','31.41');
insert into afarma.produto_afarma (nome, valor) values ('LEVOFLOXACINO 500MG C/7','23.47');
insert into afarma.produto_afarma (nome, valor) values ('LEVOTIROXINA SODICA  100MCG 30CPR','5.27');
insert into afarma.produto_afarma (nome, valor) values ('LEVOTIROXINA SODICA  112MCG 30CPR','10.43');
insert into afarma.produto_afarma (nome, valor) values ('LEVOTIROXINA SODICA  125MCG C/30','7.7');
insert into afarma.produto_afarma (nome, valor) values ('LEVOTIROXINA SODICA  25MCG 30CPR','5.92');
insert into afarma.produto_afarma (nome, valor) values ('LEVOTIROXINA SODICA  38MCG 30CPR','8.86');
insert into afarma.produto_afarma (nome, valor) values ('LEVOTIROXINA SODICA  50MCG 30CPR','6.17');
insert into afarma.produto_afarma (nome, valor) values ('LEVOTIROXINA SODICA  75MCG 30CPR','6.76');
insert into afarma.produto_afarma (nome, valor) values ('LEVOTIROXINA SODICA  88MG 30CPR','8.17');
insert into afarma.produto_afarma (nome, valor) values ('LEVOTIROXINA SODICA 37,5MCG','5.1');
insert into afarma.produto_afarma (nome, valor) values ('LIDOCAINA  20MG/G USO URETRAL                                  ','5.76');
insert into afarma.produto_afarma (nome, valor) values ('LIPIDIL 160MG 30CPR','113.13');
insert into afarma.produto_afarma (nome, valor) values ('LIVEPAX 750 C/7','69.14');
insert into afarma.produto_afarma (nome, valor) values ('LORATADINA 10MG C/12','7.99');
insert into afarma.produto_afarma (nome, valor) values ('LORAZEPAM  2MG C/20','8.99');
insert into afarma.produto_afarma (nome, valor) values ('LOSARTANA +HCTZ 50/12,5MG C/30','13.49');
insert into afarma.produto_afarma (nome, valor) values ('LOSARTANA POTASSICA 100MG C/30','14.91');
insert into afarma.produto_afarma (nome, valor) values ('LOSARTANA POTASSICA 50MG C/30','3.99');
insert into afarma.produto_afarma (nome, valor) values ('LUTEVIT OMEGA PLUS C/30','48.58');
insert into afarma.produto_afarma (nome, valor) values ('LUVA DE LÁTEX COM AMIDO C/100','33.97');
insert into afarma.produto_afarma (nome, valor) values ('LUVA VINIL MEDICAL SEM AMIDO C/100','25.9');
insert into afarma.produto_afarma (nome, valor) values ('MACRODANTINA 100MG 28CAPS','12.5');
insert into afarma.produto_afarma (nome, valor) values ('MAGNEN B6 30CPR','90.21');
insert into afarma.produto_afarma (nome, valor) values ('MALEATO DE TIMOLOL 0,5% SOL OFT','4.83');
insert into afarma.produto_afarma (nome, valor) values ('MARESIS AR 100ML','47.59');
insert into afarma.produto_afarma (nome, valor) values ('MELLERIL 25MG C/20','14.45');
insert into afarma.produto_afarma (nome, valor) values ('MEMANTINA 10MG 30CPR','27.5');
insert into afarma.produto_afarma (nome, valor) values ('MEMANTINA 10MG 60CPR','47.7');
insert into afarma.produto_afarma (nome, valor) values ('MESIL DOXAZOSINA 2MG C 30 CP ','10.97');
insert into afarma.produto_afarma (nome, valor) values ('METAMUCIL C/10 ENVELOPES','38.2');
insert into afarma.produto_afarma (nome, valor) values ('METFORMINA 500MG C/30','5.99');
insert into afarma.produto_afarma (nome, valor) values ('METFORMINA 850MG C/30','6.09');
insert into afarma.produto_afarma (nome, valor) values ('METILDOPA 250MG C/30','17.68');
insert into afarma.produto_afarma (nome, valor) values ('METOPROLOL 50 MG C/30','28.89');
insert into afarma.produto_afarma (nome, valor) values ('MICARDIS ANLO 80/5MG 30CPR','125.42');
insert into afarma.produto_afarma (nome, valor) values ('MICONAZOL CREME 28G','7.12');
insert into afarma.produto_afarma (nome, valor) values ('MILGAMMA 150MG 30 DRAGAES','68.38');
insert into afarma.produto_afarma (nome, valor) values ('MIRTAZAPINA 15MG C/30','46.85');
insert into afarma.produto_afarma (nome, valor) values ('MIRTAZAPINA 30MG 30CP','79.56');
insert into afarma.produto_afarma (nome, valor) values ('MIRTAZAPINA 45MG 30 COMP','107.01');
insert into afarma.produto_afarma (nome, valor) values ('MONOCORDIL 20MG C/30','12.89');
insert into afarma.produto_afarma (nome, valor) values ('MOTORE 250MG C/60','102.19');
insert into afarma.produto_afarma (nome, valor) values ('MOVIMENT C/30 SASHES 12G','115.34');
insert into afarma.produto_afarma (nome, valor) values ('MUPIROCINA 15G POMADA','31.13');
insert into afarma.produto_afarma (nome, valor) values ('NEOMICINA + BACITRACINA 15G','7.99');
insert into afarma.produto_afarma (nome, valor) values ('NEOVITE MAX C/30','139.98');
insert into afarma.produto_afarma (nome, valor) values ('NEOZINE 20ML GTS','14.95');
insert into afarma.produto_afarma (nome, valor) values ('NEUTROFER 150 C/30','28.71');
insert into afarma.produto_afarma (nome, valor) values ('NEUTROFER 500 C/30','71.15');
insert into afarma.produto_afarma (nome, valor) values ('NEUTROFER FÓLICO 150/5 C/30','35.39');
insert into afarma.produto_afarma (nome, valor) values ('NIFEDIPRESS RETARD 20MG 30CPR ','9.99');
insert into afarma.produto_afarma (nome, valor) values ('NIMEGON 50MG COM REV 28  COMP.','109.82');
insert into afarma.produto_afarma (nome, valor) values ('NIMESULIDA C/12','5.19');
insert into afarma.produto_afarma (nome, valor) values ('NISTATINA + OXIDO ZINCO 60G','11.14');
insert into afarma.produto_afarma (nome, valor) values ('NISTATINA SOLUÇÃO 50ML','13.88');
insert into afarma.produto_afarma (nome, valor) values ('NITROFURANTOINA 100MG C/28','8.37');
insert into afarma.produto_afarma (nome, valor) values ('NORIPURUM 100MG 30CPR MASTIGAVEL','53.53');
insert into afarma.produto_afarma (nome, valor) values ('NOVALGINA 1G C/10','19.99');
insert into afarma.produto_afarma (nome, valor) values ('NOVOPRAZOL 20MG C/28','10.13');
insert into afarma.produto_afarma (nome, valor) values ('NUTREN CELLTRIENT LIMAO C/30 SCH','114.69');
insert into afarma.produto_afarma (nome, valor) values ('OLANZAPINA 10MG C/30','71.9');
insert into afarma.produto_afarma (nome, valor) values ('OLANZAPINA 2,5MG C/30','36.98');
insert into afarma.produto_afarma (nome, valor) values ('OLANZAPINA 5MG C/28','55.25');
insert into afarma.produto_afarma (nome, valor) values ('OLÉO DE AMENDOAS','7.83');
insert into afarma.produto_afarma (nome, valor) values ('OLMESA+ HCTZ 20 + 12,5MG CPRV CT BL AL 2X15','25.28');
insert into afarma.produto_afarma (nome, valor) values ('OLMESARTANA MEDOXOMILA 20MG C/30','23.94');
insert into afarma.produto_afarma (nome, valor) values ('OMEGA 3  1.000MG C/120 CPR','27.99');
insert into afarma.produto_afarma (nome, valor) values ('OMEPRAZOL 20MG C/28 CPS','9.99');
insert into afarma.produto_afarma (nome, valor) values ('OMEPRAZOL 40MG C/28 CPS','46.14');
insert into afarma.produto_afarma (nome, valor) values ('ONDANSETRONA 4MG 10CPR','16.19');
insert into afarma.produto_afarma (nome, valor) values ('ONDANSETRONA 8MG C/10 ','29.9');
insert into afarma.produto_afarma (nome, valor) values ('OSSOTRAT PLUS  C/60','25.13');
insert into afarma.produto_afarma (nome, valor) values ('OSSOTRAT-D 600D 60CPPR ','29.99');
insert into afarma.produto_afarma (nome, valor) values ('OTOSPORIN 10ML','12.69');
insert into afarma.produto_afarma (nome, valor) values ('PANTOPRAZOL  20MG 28CPR','12.78');
insert into afarma.produto_afarma (nome, valor) values ('PANTOPRAZOL  40MG 28CPR','21.98');
insert into afarma.produto_afarma (nome, valor) values ('PANTOPRAZOL  40MG 42CPR','32.97');
insert into afarma.produto_afarma (nome, valor) values ('PARACETAMOL 200MG/ML','5.98');
insert into afarma.produto_afarma (nome, valor) values ('PARACETAMOL 500MG C/20','5.94');
insert into afarma.produto_afarma (nome, valor) values ('PARACETAMOL 750 MG C/20','4.27');
insert into afarma.produto_afarma (nome, valor) values ('PAROXETINA 20MG C/30','20.11');
insert into afarma.produto_afarma (nome, valor) values ('PEG-LAX PO 8,5G C/14 ENV','26.5');
insert into afarma.produto_afarma (nome, valor) values ('PEG-LAX PO C 14 ENV','34.9');
insert into afarma.produto_afarma (nome, valor) values ('PEN-VE-ORAL  500.000 UI  C/12','20.15');
insert into afarma.produto_afarma (nome, valor) values ('PIOGLITAZONA 30 MG C/30 ','78.17');
insert into afarma.produto_afarma (nome, valor) values ('PIOLETAL PLUS 5 - 60ML','29.99');
insert into afarma.produto_afarma (nome, valor) values ('PLASIL 10MG C/20','9.49');
insert into afarma.produto_afarma (nome, valor) values ('PRADAXA 150MG C/60','240.36');
insert into afarma.produto_afarma (nome, valor) values ('PREDNISONA 20MG C/20','12.4');
insert into afarma.produto_afarma (nome, valor) values ('PREDNISONA 5MG C/20','7.5');
insert into afarma.produto_afarma (nome, valor) values ('PREGABALINA 50MG C/30','63.85');
insert into afarma.produto_afarma (nome, valor) values ('PREGABALINA 75MG 28CPR','35.78');
insert into afarma.produto_afarma (nome, valor) values ('PRESSAT 2,5MG','27.35');
insert into afarma.produto_afarma (nome, valor) values ('PRESSPLUS 5MG/10MG C/30','77.64');
insert into afarma.produto_afarma (nome, valor) values ('PROBENXIL 60G ','10.13');
insert into afarma.produto_afarma (nome, valor) values ('PROFERGAN 25MG 20CPR ','4.99');
insert into afarma.produto_afarma (nome, valor) values ('PROLOPA 100/25 MG 30CPR','64.25');
insert into afarma.produto_afarma (nome, valor) values ('PROLOPA 200/50 MG 30CPR','94.12');
insert into afarma.produto_afarma (nome, valor) values ('PROLOPA BD 100/25MG C/30','43.29');
insert into afarma.produto_afarma (nome, valor) values ('PROLOPA HBS 125MG 30CPS','64.25');
insert into afarma.produto_afarma (nome, valor) values ('PROMETAZINA 25MG','4.99');
insert into afarma.produto_afarma (nome, valor) values ('PROPAFENONA 300MG','32.98');
insert into afarma.produto_afarma (nome, valor) values ('PROPRANOLOL 40MG C/30','3.36');
insert into afarma.produto_afarma (nome, valor) values ('PROTEFIGAM SM 100MG C/30','44.99');
insert into afarma.produto_afarma (nome, valor) values ('PROTEFIGAM SM 200MG C/20','41.82');
insert into afarma.produto_afarma (nome, valor) values ('PROTETOR SOLAR FPS 60  120ML','29.9');
insert into afarma.produto_afarma (nome, valor) values ('PRYSMA 2MG C/20 COMP.','60.39');
insert into afarma.produto_afarma (nome, valor) values ('PULMICORT 05MG 20FRASCOS 2ML','212.13');
insert into afarma.produto_afarma (nome, valor) values ('PURAN T4 12,5 30CPR','2.69');
insert into afarma.produto_afarma (nome, valor) values ('PURAN T4 37,5 30CPR','7.94');
insert into afarma.produto_afarma (nome, valor) values ('QUETIAPINA  100MG 30','63.42');
insert into afarma.produto_afarma (nome, valor) values ('QUETIAPINA  25MG 30CPR','19.99');
insert into afarma.produto_afarma (nome, valor) values ('QUETIAPINA  50MG 30CPR','105.43');
insert into afarma.produto_afarma (nome, valor) values ('RAPILAX GOTAS','12.48');
insert into afarma.produto_afarma (nome, valor) values ('RAZAPINA ODT 15MG C/28','59.22');
insert into afarma.produto_afarma (nome, valor) values ('REMILEV 20CPR','49.97');
insert into afarma.produto_afarma (nome, valor) values ('REPELENTE XÔ INSETO 200 ML','12.99');
insert into afarma.produto_afarma (nome, valor) values ('RESIST 500MG 30CPS','43.19');
insert into afarma.produto_afarma (nome, valor) values ('RESIST 500MG 90CPS','125.21');
insert into afarma.produto_afarma (nome, valor) values ('RESOLOR 2 MG C/14','127.49');
insert into afarma.produto_afarma (nome, valor) values ('RETEMIC 5MG C/30','30.19');
insert into afarma.produto_afarma (nome, valor) values ('RETEMIC 5MG C/60','47.96');
insert into afarma.produto_afarma (nome, valor) values ('RIFAMICINA SPRAY','12.22');
insert into afarma.produto_afarma (nome, valor) values ('RISPERIDONA 1MG C/30','17.23');
insert into afarma.produto_afarma (nome, valor) values ('RISPERIDONA 1MG SOL ORAL','39.53');
insert into afarma.produto_afarma (nome, valor) values ('RISPERIDONA 2MG C/30','19.57');
insert into afarma.produto_afarma (nome, valor) values ('RISPERIDONA 3MG','19.9');
insert into afarma.produto_afarma (nome, valor) values ('RITMONEURAN C/20','22.41');
insert into afarma.produto_afarma (nome, valor) values ('RIVAROXABANA 10MG C/30','131.24');
insert into afarma.produto_afarma (nome, valor) values ('RIVAROXABANA 15MG C/28','124.49');
insert into afarma.produto_afarma (nome, valor) values ('RIVAROXABANA 20MG C/28','122.45');
insert into afarma.produto_afarma (nome, valor) values ('RIVOTRIL 0,5 C/30','16.53');
insert into afarma.produto_afarma (nome, valor) values ('RIVOTRIL 0.25 C/30 COMP SUBLINGUAIS','8.35');
insert into afarma.produto_afarma (nome, valor) values ('RIVOTRIL 2,5MG - 20 ML','22.29');
insert into afarma.produto_afarma (nome, valor) values ('RIVOTRIL 2MG C/20 COMP','19.21');
insert into afarma.produto_afarma (nome, valor) values ('ROSUVASTATINA CALCICA 10MG C/30','27.2');
insert into afarma.produto_afarma (nome, valor) values ('ROSUVASTATINA CALCICA 20MG C/30','36.79');
insert into afarma.produto_afarma (nome, valor) values ('SABONETE BARRA 85G','1.98');
insert into afarma.produto_afarma (nome, valor) values ('SABONETE LÍQUIDO 2L DETAGOLD','15.99');
insert into afarma.produto_afarma (nome, valor) values ('SANISKIN LC 100ML','38.05');
insert into afarma.produto_afarma (nome, valor) values ('SECNIDAZOL 1000 MG  C/2','7.65');
insert into afarma.produto_afarma (nome, valor) values ('SELOZOK 50MG C 30COMP','56.88');
insert into afarma.produto_afarma (nome, valor) values ('SERTRALINA 100MG 30CPR','35.77');
insert into afarma.produto_afarma (nome, valor) values ('SERTRALINA 50MG 30CPR','21.02');
insert into afarma.produto_afarma (nome, valor) values ('SHAMPOO 350 ML','6.99');
insert into afarma.produto_afarma (nome, valor) values ('SIMETICONA 40MG 20CPR','5.14');
insert into afarma.produto_afarma (nome, valor) values ('SIMETICONA 75MG/ML','5.78');
insert into afarma.produto_afarma (nome, valor) values ('SINVASTATINA 20MG C/30','6.15');
insert into afarma.produto_afarma (nome, valor) values ('SINVASTATINA 40MG C/30','9.91');
insert into afarma.produto_afarma (nome, valor) values ('SLOW K - C/20','13.69');
insert into afarma.produto_afarma (nome, valor) values ('SOMALGIN CARDIO 100MG C/60','40.61');
insert into afarma.produto_afarma (nome, valor) values ('SOTALOL  120MG 30CPR','25.35');
insert into afarma.produto_afarma (nome, valor) values ('SOTALOL  160MG 20CPR','24.65');
insert into afarma.produto_afarma (nome, valor) values ('STEATON 200MG 60CPR','117.99');
insert into afarma.produto_afarma (nome, valor) values ('STILNOX 10MG C/20','57.79');
insert into afarma.produto_afarma (nome, valor) values ('SULFATO DE MORFINA 10MG C/50','39.87');
insert into afarma.produto_afarma (nome, valor) values ('SULFATO DE SALBUTAMOL SPRAY 200 DOSES ','14.78');
insert into afarma.produto_afarma (nome, valor) values ('SULFATO FERROSO 40MG C/50','21.89');
insert into afarma.produto_afarma (nome, valor) values ('SUPRA D 500 UI - 10 ML','22.68');
insert into afarma.produto_afarma (nome, valor) values ('SUPRA SENIOR 400G','41.12');
insert into afarma.produto_afarma (nome, valor) values ('SUPUSITORIO DE GLICERINA ADULTO C/6','13.89');
insert into afarma.produto_afarma (nome, valor) values ('SYSTANE UL 10ML','44.84');
insert into afarma.produto_afarma (nome, valor) values ('TALCO BARLA 85G','5.39');
insert into afarma.produto_afarma (nome, valor) values ('TAMARETI GELEIA 150G','44.99');
insert into afarma.produto_afarma (nome, valor) values ('TAMARINE GEL LAX POTE 150G','55.14');
insert into afarma.produto_afarma (nome, valor) values ('TANSULOSINA 0,4MG C/30','57.75');
insert into afarma.produto_afarma (nome, valor) values ('TEGUM 100GR','58.9');
insert into afarma.produto_afarma (nome, valor) values ('TENAVIT 30CPR','72.89');
insert into afarma.produto_afarma (nome, valor) values ('TIAMINA 300MG','16.49');
insert into afarma.produto_afarma (nome, valor) values ('TICLOPIDINA 250MG C/30','52.3');
insert into afarma.produto_afarma (nome, valor) values ('TIORFAN 100MG 9CPS','39.99');
insert into afarma.produto_afarma (nome, valor) values ('TIRAS G TECH FREE C/50','79.9');
insert into afarma.produto_afarma (nome, valor) values ('TORSILAX 30CPR','16.99');
insert into afarma.produto_afarma (nome, valor) values ('TORVAL CR 300MG C/60','46.59');
insert into afarma.produto_afarma (nome, valor) values ('TRAMADOL 50MG 10 CAPSULAS','13.99');
insert into afarma.produto_afarma (nome, valor) values ('TRAZODONA  50MG 60CPR','39.24');
insert into afarma.produto_afarma (nome, valor) values ('TRAZODONA 50MG 60CPR','39.24');
insert into afarma.produto_afarma (nome, valor) values ('TYLEX C/36','78.99');
insert into afarma.produto_afarma (nome, valor) values ('ULTRAFER 100MG C/30','49.39');
insert into afarma.produto_afarma (nome, valor) values ('UMCKAN 800MG 50ML','99.79');
insert into afarma.produto_afarma (nome, valor) values ('UNINALTREX 50MG C/30','113.52');
insert into afarma.produto_afarma (nome, valor) values ('VAGI-C 6CPR 1APL','43.49');
insert into afarma.produto_afarma (nome, valor) values ('VAL BETAM+SUL GENT+TOLNAF+CLIOQ POM BG 20G','13.95');
insert into afarma.produto_afarma (nome, valor) values ('VALPROATO SODIO  500MG 50CPR','47.19');
insert into afarma.produto_afarma (nome, valor) values ('VALPROATO XAROPE 250MG/5ML','11.89');
insert into afarma.produto_afarma (nome, valor) values ('VALSARTANA 160MG CX 30 COMP ','29.99');
insert into afarma.produto_afarma (nome, valor) values ('VALSARTANA 80MG 30CPR','29.59');
insert into afarma.produto_afarma (nome, valor) values ('VECASTEN 26,7MG 30CPR','93.64');
insert into afarma.produto_afarma (nome, valor) values ('VELUS MAG C/30 ','93.39');
insert into afarma.produto_afarma (nome, valor) values ('VENAFLON 450/50MG 30CPR','32.49');
insert into afarma.produto_afarma (nome, valor) values ('VENLAFAXINA 150MG 30CPS','52.68');
insert into afarma.produto_afarma (nome, valor) values ('VENLAFAXINA 37,5MG 28CPR','22.17');
insert into afarma.produto_afarma (nome, valor) values ('VENLAFAXINA 75MG 30CPR','41.99');
insert into afarma.produto_afarma (nome, valor) values ('VIC VAPORUBE 30G','28.42');
insert into afarma.produto_afarma (nome, valor) values ('VICOG 30CPR','24.99');
insert into afarma.produto_afarma (nome, valor) values ('VIDISIC GEL 10GR','46.39');
insert into afarma.produto_afarma (nome, valor) values ('VITAMAX MB6 C/30','55.29');
insert into afarma.produto_afarma (nome, valor) values ('VITAMINA B12 CONCENTRADA C/60 CAPS','25.32');
insert into afarma.produto_afarma (nome, valor) values ('VITAMINA C 500MG C/ 20 COMP.','8.79');
insert into afarma.produto_afarma (nome, valor) values ('VITAMINA D 1.000UI C/30 CAP','16.42');
insert into afarma.produto_afarma (nome, valor) values ('VITAMINA D3 10.000 UI C/4','19.99');
insert into afarma.produto_afarma (nome, valor) values ('VITAMINA D3 10.000 UI C/8','29.79');
insert into afarma.produto_afarma (nome, valor) values ('VITAMINA D3 10.000UI 30CPS ','69.5');
insert into afarma.produto_afarma (nome, valor) values ('VITAMINA D3 2.000UI C/30','18.58');
insert into afarma.produto_afarma (nome, valor) values ('VITAMINA D3 50.000UI C/4','29.9');
insert into afarma.produto_afarma (nome, valor) values ('VITAMINA D3 7.000UI C/10','14.97');
insert into afarma.produto_afarma (nome, valor) values ('VITAMINA D3 7.000UI C/8','12.99');
insert into afarma.produto_afarma (nome, valor) values ('VITAMINA E 400MG C/30','18.74');
insert into afarma.produto_afarma (nome, valor) values ('VITERGAN ZINCO C/30 ','78.9');
insert into afarma.produto_afarma (nome, valor) values ('VITERGAN ZINCO PLUS C/30','87.44');
insert into afarma.produto_afarma (nome, valor) values ('ZOLPIDEM 10MG 30CPR','25.98');
insert into afarma.produto_afarma (nome, valor) values ('ZOLPIDEM 10MG C/20','15.62');
insert into afarma.produto_afarma (nome, valor) values ('ZOLPIDEM 10MG C/30','19.2');
insert into afarma.produto_afarma (nome, valor) values ('ZOUP SL 5MG C/30','53.51');
insert into afarma.produto_afarma (nome, valor) values ('DESLORATADINA 5MG C/10','14.99');
insert into afarma.produto_afarma (nome, valor) values ('Benicar HCT 20mg+12,5   C/30','22.09');
insert into afarma.produto_afarma (nome, valor) values ('CETOCONAZOL 20MG + DIPROPIONATO DE BETAMETASONA 0,64MG + SULFATO DE NEOMICINA 2,5MG CREME DERMATOLÓGICO COM 30G','13.99');
insert into afarma.produto_afarma (nome, valor) values ('TRIMETAZIDINA 35MG C/30','78.67');
insert into afarma.produto_afarma (nome, valor) values ('VALERIANA OFFICINALISS 50MG C/20','6.3');
insert into afarma.produto_afarma (nome, valor) values ('RAZAPINA 30MG C/30','88.87');
insert into afarma.produto_afarma (nome, valor) values ('NEBLOCK 5MG C/60','69.9');
insert into afarma.produto_afarma (nome, valor) values ('VENZER HCT 16/12,5 MG C/30','64.83');
insert into afarma.produto_afarma (nome, valor) values ('TOTAVIT 10+2MG C/30','99.32');
insert into afarma.produto_afarma (nome, valor) values ('CLORETO MAGNESIO 500MG C/60','28.9');
insert into afarma.produto_afarma (nome, valor) values ('LEVOID 150MG C/30','9.92');
insert into afarma.produto_afarma (nome, valor) values ('MEMANTINA 20MG C/30','149.99');
insert into afarma.produto_afarma (nome, valor) values ('LAMOTRIGINA 100MG 30CP','20.2');
insert into afarma.produto_afarma (nome, valor) values ('ICADEN SOL 30ML','51.42');
insert into afarma.produto_afarma (nome, valor) values ('VITAMINA C 1G ENV C/30','39.19');
insert into afarma.produto_afarma (nome, valor) values ('COGLIVE 8 MG 30 CAP','144.81');
insert into afarma.produto_afarma (nome, valor) values ('DESVENLAFAXIN 50MG 30C','65.92');
insert into afarma.produto_afarma (nome, valor) values ('JANUMET XR 50MG+1000MG C/60 ','223.55');
insert into afarma.produto_afarma (nome, valor) values ('GLIMEPIRIDA 4MG C/30','17.35');
insert into afarma.produto_afarma (nome, valor) values ('SIMETICONA 125MG C/10','10.62');
insert into afarma.produto_afarma (nome, valor) values ('CLORTALIDONA 12,5MG C/60','12.81');
insert into afarma.produto_afarma (nome, valor) values ('DIAZEPAM 10MG C/30','9.65');
insert into afarma.produto_afarma (nome, valor) values ('GABAPENTINA 300MG CAP X 30','29.99');
insert into afarma.produto_afarma (nome, valor) values ('NEOZINE 100MG C 20','22.09');
