
-- public.generico_grupo definition

-- Drop table

-- DROP TABLE public.generico_grupo;

CREATE TABLE public.generico_grupo (
	id varchar(36) NOT NULL DEFAULT uuid_generate_v4(),
	grupo varchar(255) NULL,
	"name" varchar(255) NULL
);






insert into generico_grupo(grupo,name) values ('1','Anastrozol 1mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('2','Bicalutamida 50mg  - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3','Citrato de Tamoxifeno 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('5','Letrozol 2,5mg - 30 Comprimidos ');
insert into generico_grupo(grupo,name) values ('6','Cimetidina 200mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('7','Cimetidina 200mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('8','Cimetidina 400mg - 16 Comprimidos');
insert into generico_grupo(grupo,name) values ('11','Montelucaste de Sódio 4mg - 30 comprimidos');
insert into generico_grupo(grupo,name) values ('15','Esomeprazol 20mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('16','Esomeprazol 20mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('17','Esomeprazol 40mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('18','Esomeprazol 40mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('19','Lansoprazol 15mg - 28 Cápsulas');
insert into generico_grupo(grupo,name) values ('20','Lansoprazol 30mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('21','Lansoprazol 30mg - 28 Cápsulas');
insert into generico_grupo(grupo,name) values ('23','Omeprazol 20mg - 56 Cápsulas');
insert into generico_grupo(grupo,name) values ('24','Omeprazol 20mg - 28 Cápsulas');
insert into generico_grupo(grupo,name) values ('25','Omeprazol 20mg - 7 Cápsulas');
insert into generico_grupo(grupo,name) values ('26','Omeprazol 20mg - 14 Cápsulas');
insert into generico_grupo(grupo,name) values ('27','Omeprazol 20mg - 42 Cápsulas');
insert into generico_grupo(grupo,name) values ('28','Omeprazol 40mg - 7 Cápsulas');
insert into generico_grupo(grupo,name) values ('29','Pantoprazol 20mg - 42 Comprimidos');
insert into generico_grupo(grupo,name) values ('30','Pantoprazol 20mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('31','Pantoprazol 20mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('33','Pantoprazol 20mg - 7 Comprimidos');
insert into generico_grupo(grupo,name) values ('34','Pantoprazol 40mg - 42 Comprimidos');
insert into generico_grupo(grupo,name) values ('35','Pantoprazol 40mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('36','Pantoprazol 40mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('37','Simeticona 125mg - 10 Cápsulas');
insert into generico_grupo(grupo,name) values ('38','Simeticona 40mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('39','Simeticona 75mg Gotas 15ml');
insert into generico_grupo(grupo,name) values ('41','Triancinolona Pomada Bucal - 10g');
insert into generico_grupo(grupo,name) values ('42','Nistatina 100.000UI/ml Suspensão Oral - 50ml');
insert into generico_grupo(grupo,name) values ('43','Bromoprida 10mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('44','Bromoprida Solução Oral 4mg/ml - 20ml');
insert into generico_grupo(grupo,name) values ('46','Domperidona 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('47','Domperidona 10mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('48','Domperidona 1mg/ml - 100ml');
insert into generico_grupo(grupo,name) values ('49','Brometo de Pinavério 100mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('50','Brometo de Pinavério 100mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('51','Cloridrato de Loperamida 2mg - 12 Comprimidos');
insert into generico_grupo(grupo,name) values ('52','Maleato De Trimebutina 200mg - 30 Cápsulas');
insert into generico_grupo(grupo,name) values ('53','Maleato De Trimebutina 200mg - 60 Cápsulas');
insert into generico_grupo(grupo,name) values ('54','Mesalazina 400mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('55','Mesalazina 800mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('57','Cloridrato de Fexofenadina 120mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('58','Cloridrato de Fexofenadina 180mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('59','Cloridrato de Hidroxizina 25mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('60','Budesonida 32mcg - 120 Doses Spray Nasal');
insert into generico_grupo(grupo,name) values ('61','Budesonida 64mcg - 120 Doses Spray Nasal');
insert into generico_grupo(grupo,name) values ('65','Desloratadina 0,5mg/ml - Xarope 60ml');
insert into generico_grupo(grupo,name) values ('66','Desloratadina 0,5mg/ml - Xarope 100ml');
insert into generico_grupo(grupo,name) values ('67','Desloratadina 5mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('68','Desloratadina 5mg Genérico - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('69','Dicloridrato De Levocetirizina 5mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('70','Loratadina 10mg - 12 Comprimidos');
insert into generico_grupo(grupo,name) values ('71','Loratadina Xarope 1mg/Ml - 100ml');
insert into generico_grupo(grupo,name) values ('74','Maleato de Dexclorfeniramina 0,4mg/ml Xarope - 120ml');
insert into generico_grupo(grupo,name) values ('75','Maleato de Dexclorfeniramina 2mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('77','Dropropizina Xarope 3,0mg/ml - 120ml');
insert into generico_grupo(grupo,name) values ('78','Cloridrato de Nafazolina 5mg/ml - 30ml');
insert into generico_grupo(grupo,name) values ('79','Cloridrato de Oximetazolina Adulto 0,5mg/ml - 30ml');
insert into generico_grupo(grupo,name) values ('80','Cloridrato de Oximetazolina Pediátrico 0,25mg/ml - 20ml');
insert into generico_grupo(grupo,name) values ('83','Acebrofilina 50mg/5ml - Xarope Adulto 120ml');
insert into generico_grupo(grupo,name) values ('86','Acetilcisteína 100mg - 16 Sachês');
insert into generico_grupo(grupo,name) values ('87','Acetilcisteína 200mg - 16 Sachês');
insert into generico_grupo(grupo,name) values ('89','Acetilcisteína 600mg - 16 Sachês');
insert into generico_grupo(grupo,name) values ('90','Acetilcisteína Xarope 20mg/ml - 150ml');
insert into generico_grupo(grupo,name) values ('91','Acetilcisteína 40mg/ml Xarope Adulto - 120ml');
insert into generico_grupo(grupo,name) values ('93','Acetilcisteína Infantil 20mg/ml Xarope - 120ml');
insert into generico_grupo(grupo,name) values ('95','Carbocisteina Adulto 50mg/ml  - 100ml');
insert into generico_grupo(grupo,name) values ('96','Carbocisteina Pediátrico 20mg/ml - 100ml');
insert into generico_grupo(grupo,name) values ('97','Cloridrato de Ambroxol Xarope 6mg/ml - 120ml');
insert into generico_grupo(grupo,name) values ('98','Cloridrato de Ambroxol 3mg/ml - Xarope Pediátrico 120ml');
insert into generico_grupo(grupo,name) values ('100','Cloridrato de Bromexina Xarope Infantil 4mg - 120ml');
insert into generico_grupo(grupo,name) values ('102','Aminofilina 100mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('103','Aminofilina 200mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('104','Brometo de Ipatrópio 0,25mg/ml - 20ml');
insert into generico_grupo(grupo,name) values ('105','Fumarato de Cetotifeno Gotas 1mg/ml - 30ml');
insert into generico_grupo(grupo,name) values ('108','Montelucaste de Sódio 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('110','Montelucaste de Sódio 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('113','Atenolol 100mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('114','Atenolol 25mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('115','Atenolol 25mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('116','Atenolol 50mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('122','Besilato de Anlodipino 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('123','Besilato de Anlodipino 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('125','Hemifumarato de Bisoprolol 1,25mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('126','Hemifumarato de Bisoprolol 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('128','Hemifumarato de Bisoprolol 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('131','Candesartana Cilexetila 16mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('132','Candesartana Cilexetila 8mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('133','Captopril 12,5 mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('134','Captopril 25mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('135','Captopril 25mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('136','Captopril 50mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('138','Carvedilol 12,5mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('139','Carvedilol 12,5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('141','Carvedilol 25mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('142','Carvedilol 25mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('144','Carvedilol 3,125mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('145','Carvedilol 3,125mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('147','Carvedilol 6,25mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('148','Carvedilol 6,25mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('149','Cloridrato de Lercanidipino 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('150','Cloridrato de Nebivolol 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('152','Cloridrato de Nebivolol 5mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('153','Cloridrato de Propranolol 10mg - 30 comprimidos');
insert into generico_grupo(grupo,name) values ('154','Cloridrato de Propranolol 40mg - 30 comprimidos');
insert into generico_grupo(grupo,name) values ('156','Cloridrato de Sotalol 120mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('157','Cloridrato de Sotalol 160mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('158','Cloridrato de Sotalol 160mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('163','Irbesartana 150mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('165','Lisinopril 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('166','Lisinopril 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('167','Lisinopril 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('169','Losartana Potássica 100mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('170','Losartana Potássica 50mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('171','Losartana Potássica 50mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('176','Maleato de Enalapril 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('177','Maleato de Enalapril 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('178','Maleato de Enalapril 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('179','Mesilato de Doxazosina 2mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('180','Mesilato de Doxazosina 4mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('181','Metildopa 250mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('182','Metildopa 500mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('186','Nitrendipino 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('187','Nitrendipino 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('191','Olmesartana Medoxomila 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('192','Olmesartana Medoxomila 40mg - 30 comprimidos');
insert into generico_grupo(grupo,name) values ('195','Ramipril 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('196','Ramipril 5mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('198','Succinato de Metoprolol 100mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('199','Succinato de Metoprolol 25mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('200','Succinato de Metoprolol 50mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('201','Tartarato de Metoprolol 100mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('203','Telmisartana 80mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('211','Bissulfato de Clopidogrel 75mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('212','Bissulfato de Clopidogrel 75mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('213','Bissulfato de Clopidogrel 75mg - 56 Comprimidos');
insert into generico_grupo(grupo,name) values ('214','Cilostazol 100mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('215','Cilostazol 100mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('216','Cilostazol 50mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('217','Cilostazol 50mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('219','Cloridrato de Ticlopidina 250mg -20 Comprimidos');
insert into generico_grupo(grupo,name) values ('221','Atorvastatina Cálcica 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('226','Atorvastatina Cálcica 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('228','Atorvastatina Cálcica 40mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('229','Atorvastatina Cálcica 80mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('230','Bezafibrato 200mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('231','Ciprofibrato 100mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('235','Ezetimiba 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('236','Ezetimiba 10mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('237','Fenofibrato 200mg - 30 Cápsulas');
insert into generico_grupo(grupo,name) values ('238','Genfibrozila 600mg - 24 Comprimidos');
insert into generico_grupo(grupo,name) values ('239','Genfibrozila 600mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('240','Genfibrozila 900mg - 12 Comprimidos');
insert into generico_grupo(grupo,name) values ('241','Genfibrozila 900mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('242','Pravastatina Sódica 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('243','Pravastatina Sódica 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('244','Pravastatina Sódica 40mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('247','Rosuvastatina Cálcica 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('248','Rosuvastatina Cálcica 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('249','Rosuvastatina Cálcica 10mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('250','Rosuvastatina Cálcica 20mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('251','Rosuvastatina Cálcica 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('252','Rosuvastatina Cálcica 5mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('253','Sinvastatina 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('254','Sinvastatina 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('256','Sinvastatina 40mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('257','Sinvastatina 80mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('260','Clortalidona 12,5mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('261','Clortalidona 25mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('262','Clortalidona 50mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('263','Espironolactona 100mg - 16 comprimidos');
insert into generico_grupo(grupo,name) values ('264','Espironolactona 100mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('265','Espironolactona 25mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('266','Espironolactona 50mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('267','Furosemida 40mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('268','Furosemida 40mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('269','Hidroclorotiazida 25mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('270','Hidroclorotiazida 50mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('271','Indapamida 1,5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('272','Indapamida 1,5mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('273','Ácido Tranexâmico 250mg - 12 Comprimidos');
insert into generico_grupo(grupo,name) values ('274','Cinarizina 25mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('275','Cinarizina 75mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('276','Cloridrato de Propafenona 300mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('278','Cloridrato de Diltiazem 30mg - 50 Comprimidos');
insert into generico_grupo(grupo,name) values ('279','Cloridrato de Diltiazem 60mg - 25 Cápsulas');
insert into generico_grupo(grupo,name) values ('280','Cloridrato de Diltiazem 60mg - 50 Comprimidos');
insert into generico_grupo(grupo,name) values ('282','Cloridrato de Ticlopidina 250mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('283','Cloridrato de Verapamil 120mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('284','Cloridrato de Verapamil 80mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('285','Mononitrato de Isossorbida 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('286','Mononitrato De Isossorbida 20mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('287','Mononitrato de Isossorbida 40mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('288','Pentoxifilina 400mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('289','Pentoxifilina 400mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('291','Deflazacorte 30mg - 10 comprimidos');
insert into generico_grupo(grupo,name) values ('292','Deflazacorte 6mg - 20 comprimidos');
insert into generico_grupo(grupo,name) values ('293','Dexametasona 4mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('294','Dexametasona Elixir 0,1mg/ml - 100ml');
insert into generico_grupo(grupo,name) values ('295','Dexametasona Elixir 5mg - 120ml');
insert into generico_grupo(grupo,name) values ('298','Fosfato Sódico de Prednisolona 3mg - 120ml');
insert into generico_grupo(grupo,name) values ('299','Fosfato Sódico de Prednisolona 3mg - 60ml');
insert into generico_grupo(grupo,name) values ('302','Prednisolona 20mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('303','Prednisona 20mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('304','Prednisona 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('305','Prednisona 5mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('307','Adapaleno 1mg/g Gel - 30g');
insert into generico_grupo(grupo,name) values ('308','Isotretinoína 10mg - 30 Cápsulas');
insert into generico_grupo(grupo,name) values ('309','Isotretinoína 20mg - 30 Cápsulas');
insert into generico_grupo(grupo,name) values ('310','Maleato de Dexclorfeniramina 10mg - 30g');
insert into generico_grupo(grupo,name) values ('316','Rifamicina Solução Tópica Spray 10mg/ml - 20ml');
insert into generico_grupo(grupo,name) values ('319','Cetoconazol 20mg Creme - 30g');
insert into generico_grupo(grupo,name) values ('320','Cetoconazol 20mg/ml Shampoo Anticaspa - 100ml');
insert into generico_grupo(grupo,name) values ('321','Cetoconazol 20mg/ml Shampoo Anticaspa - 110ml');
insert into generico_grupo(grupo,name) values ('324','Ciclopirox Olamina Creme 10mg - 20g');
insert into generico_grupo(grupo,name) values ('325','Ciclopirox Olamina 10mg/ml - 15ml');
insert into generico_grupo(grupo,name) values ('326','Cloridrato de Terbinafina Creme 1% - 20g');
insert into generico_grupo(grupo,name) values ('329','Clotrimazol Creme Dermatológico 10mg/g - 20g');
insert into generico_grupo(grupo,name) values ('331','Nitrato de Isoconazol 10mg/g Creme Dermatológico - 20g');
insert into generico_grupo(grupo,name) values ('332','Nitrato de Miconazol 20mg - 28g Creme');
insert into generico_grupo(grupo,name) values ('333','Nitrato de Miconazol 20mg - Loção 30ml');
insert into generico_grupo(grupo,name) values ('335','Aciclovir Creme 50mg - 10g');
insert into generico_grupo(grupo,name) values ('336','Finasterida 1mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('337','Finasterida 1mg - 60 comprimidos');
insert into generico_grupo(grupo,name) values ('338','Acetato de Dexametasona Creme 1mg - 10g');
insert into generico_grupo(grupo,name) values ('341','Desonida 0,5mg/g Creme - 30g');
insert into generico_grupo(grupo,name) values ('342','Desonida 0,5mg/g Pomada - 30g');
insert into generico_grupo(grupo,name) values ('344','Dipropionato de Betametasona 0,5mg/g Creme - 30g');
insert into generico_grupo(grupo,name) values ('345','Furoato de Mometasona 1mg/g - 20g Creme');
insert into generico_grupo(grupo,name) values ('346','Furoato de Mometasona 1mg/g - 20g Pomada');
insert into generico_grupo(grupo,name) values ('347','Acetato de Hidrocortisona 10mg/g - 30g Creme');
insert into generico_grupo(grupo,name) values ('352','Gel Dermatológico Hidroquinona 40mg - 30g');
insert into generico_grupo(grupo,name) values ('353','Propionato de Clobetasol 0,5mg/g - Creme 30g');
insert into generico_grupo(grupo,name) values ('354','Propionato de Clobetasol 0,5mg/g - Pomada 30g');
insert into generico_grupo(grupo,name) values ('357','Valerato de Betametasona 1mg - 30g Creme');
insert into generico_grupo(grupo,name) values ('358','Valerato de Betametasona 1mg - Pomada 30g');
insert into generico_grupo(grupo,name) values ('359','Valerato de Betametasona 1mg/g Loção Capilar - 50g');
insert into generico_grupo(grupo,name) values ('361','Cloridrato de Metformina 500mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('362','Cloridrato de Metformina XR 750mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('363','Cloridrato de Metformina 1g - 30 comprimidos');
insert into generico_grupo(grupo,name) values ('364','Cloridrato de Metformina 500mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('365','Cloridrato de Metformina 850mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('366','Cloridrato de Metformina 850mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('369','Cloridrato de Pioglitazona 30mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('370','Cloridrato de Pioglitazona 45mg - 15 comprimidos');
insert into generico_grupo(grupo,name) values ('371','Glibenclamida 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('372','Glibenclamida 5mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('373','Gliclazida 30mg - 30 comprimidos');
insert into generico_grupo(grupo,name) values ('374','Gliclazida 30mg - 60 comprimidos');
insert into generico_grupo(grupo,name) values ('377','Glimepirida 1mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('378','Glimepirida 2mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('379','Glimepirida 2mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('380','Glimepirida 4mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('381','Repaglinida 2mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('382','Cloridrato de Sibutramina 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('383','Cloridrato de Sibutramina 15mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('384','Orlistate 120mg - 84 Capsulas');
insert into generico_grupo(grupo,name) values ('385','Orlistate 120mg - 30 Cápsulas');
insert into generico_grupo(grupo,name) values ('386','Orlistate 120mg - 60 Cápsulas');
insert into generico_grupo(grupo,name) values ('387','Orlistate 120mg - 42 Capsulas');
insert into generico_grupo(grupo,name) values ('388','Levotiroxina Sódica 100mcg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('389','Levotiroxina Sódica 112mcg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('390','Levotiroxina Sódica 125mcg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('391','Levotiroxina Sódica 150mcg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('393','Levotiroxina Sódica 175mcg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('394','Levotiroxina Sódica 200mcg - 30 comprimidos');
insert into generico_grupo(grupo,name) values ('395','Levotiroxina Sódica 25mcg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('396','Levotiroxina Sódica 50mcg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('397','Levotiroxina Sódica 75mcg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('398','Levotiroxina Sódica 88mcg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('400','Cloridrato de Naratriptana 2,5mg - 4 Comprimidos ');
insert into generico_grupo(grupo,name) values ('401','Cloridrato de Tramadol 100mg - 10ml');
insert into generico_grupo(grupo,name) values ('402','Cloridrato de Tramadol 50mg - 10 Cápsulas');
insert into generico_grupo(grupo,name) values ('408','Ácido Acetilsalicílico Infantil 100mg - 30 comprimidos');
insert into generico_grupo(grupo,name) values ('413','Dipirona Sódica 1g - 10 comprimidos');
insert into generico_grupo(grupo,name) values ('414','Dipirona Sódica 500mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('416','Dipirona Sódica 500mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('418','Dipirona Sódica 500mg - 10ml Solução Gotas');
insert into generico_grupo(grupo,name) values ('419','Dipirona Sódica 500mg - 20ml Solução Gotas');
insert into generico_grupo(grupo,name) values ('420','Dipirona Sódica Solução 50mg/ml - 100ml');
insert into generico_grupo(grupo,name) values ('422','Ibuprofeno 100mg/Ml Suspensão Oral - 20ml');
insert into generico_grupo(grupo,name) values ('423','Ibuprofeno 400mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('424','Ibuprofeno 50mg/g - 30ml Gotas');
insert into generico_grupo(grupo,name) values ('426','Paracetamol Suspensão Oral Gotas Bebê 100mg/ml - 15ml');
insert into generico_grupo(grupo,name) values ('429','Paracetamol 750mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('430','Paracetamol 750mg - 4 Comprimidos');
insert into generico_grupo(grupo,name) values ('431','Paracetamol 200mg/ml Gotas - 15ml');
insert into generico_grupo(grupo,name) values ('434','Lidocaína Creme 40mg/g - 30g');
insert into generico_grupo(grupo,name) values ('435','Lidocaína Pomada 50mg/g - 25g');
insert into generico_grupo(grupo,name) values ('436','Lidocaína 50mg/g Pomada Dermatológica Sabor Laranja - 25g');
insert into generico_grupo(grupo,name) values ('437','Aceclofenaco 100mg - 12 Comprimidos');
insert into generico_grupo(grupo,name) values ('442','Celecoxibe 200mg - 10 Cápsulas');
insert into generico_grupo(grupo,name) values ('443','Celecoxibe 200mg - 15 cápsulas');
insert into generico_grupo(grupo,name) values ('444','Celecoxibe 200mg - 30 Cápsulas');
insert into generico_grupo(grupo,name) values ('445','Cetoprofeno 100mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('446','Cetoprofeno 150mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('447','Cetoprofeno 20mg/ml Gotas - 20ml');
insert into generico_grupo(grupo,name) values ('448','Cetoprofeno Gel 25mg/g - 30g');
insert into generico_grupo(grupo,name) values ('449','Cetoprofeno 50mg - 24 Comprimidos');
insert into generico_grupo(grupo,name) values ('450','Diclofenaco de Colestiramina 70mg - 14 Cápsulas');
insert into generico_grupo(grupo,name) values ('451','Diclofenaco de Colestiramina 70mg - 20 Cápsulas');
insert into generico_grupo(grupo,name) values ('452','Diclofenaco de Dietilamônio 11,6/g - Creme 60g');
insert into generico_grupo(grupo,name) values ('453','Diclofenaco de Potássico 50mg - 10 Drágeas');
insert into generico_grupo(grupo,name) values ('454','Diclofenaco de Potássico 50mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('455','Diclofenaco Resinato Gotas 15mg - 20ml');
insert into generico_grupo(grupo,name) values ('456','Diclofenaco Sódico 100mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('457','Diclofenaco Sódico 100mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('458','Diclofenaco Sódico 50mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('459','Diclofenaco Sódico Gel 10mg/g - 60g');
insert into generico_grupo(grupo,name) values ('460','Meloxicam 15mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('461','Meloxicam 15mg/1,5ml Solução Injetável - 5 ampolas de 1,5ml');
insert into generico_grupo(grupo,name) values ('462','Meloxicam 7,5mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('463','Naproxeno 500mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('464','Nimesulida 100mg - 12 comprimidos');
insert into generico_grupo(grupo,name) values ('465','Etodolaco 400mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('466','Etodolaco 400mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('469','Nimesulida Gel 20mg - 30g');
insert into generico_grupo(grupo,name) values ('470','Nimesulida 20mg Gel - 40g');
insert into generico_grupo(grupo,name) values ('471','Nimesulida 50mg/ml Gotas - 15ml');
insert into generico_grupo(grupo,name) values ('473','Piroxicam 20mg - 15 Cápsulas');
insert into generico_grupo(grupo,name) values ('474','Tenoxicam 20mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('475','Ácido Mefenamico 500mg - 12 Comprimidos');
insert into generico_grupo(grupo,name) values ('476','Succinato de Sumatriptana 100mg - 2 Comprimidos');
insert into generico_grupo(grupo,name) values ('477','Succinato de Sumatriptana 50mg - 2 Comprimidos');
insert into generico_grupo(grupo,name) values ('478','Alopurinol 100mg - 30 Cápsulas');
insert into generico_grupo(grupo,name) values ('480','Alopurinol 300mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('483','Cloridrato de Ciclobenzaprina 10mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('484','Cloridrato de Ciclobenzaprina 10mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('485','Cloridrato de Ciclobenzaprina 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('486','Cloridrato de Ciclobenzaprina 5mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('487','Cloridrato de Ciclobenzaprina 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('488','Cloridrato de Tizanidina 2mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('534','Cefadroxila Suspensão 250mg/5ml - 100ml');
insert into generico_grupo(grupo,name) values ('535','Cefadroxila 500mg - 8 Comprimidos');
insert into generico_grupo(grupo,name) values ('536','Cefadroxila 500mg/5ml Suspensão - 100ml');
insert into generico_grupo(grupo,name) values ('537','Cefalexina 1000mg - 8 Comprimidos');
insert into generico_grupo(grupo,name) values ('539','Cefalexina 500mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('541','Cefalexina 500mg - 8 Comprimidos');
insert into generico_grupo(grupo,name) values ('542','Cefalexina Suspensão Oral 50mg/ml - 100ml');
insert into generico_grupo(grupo,name) values ('546','Claritromicina 125/5ml - 60ml');
insert into generico_grupo(grupo,name) values ('547','Claritromicina 250mg/5ml Suspensão Oral - 60ml');
insert into generico_grupo(grupo,name) values ('548','Claritromicina 500mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('549','Claritromicina 500mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('552','Cloridrato de Ciprofloxacino 500mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('553','Cloridrato de Ciprofloxacino 500mg - 6 Comprimidos');
insert into generico_grupo(grupo,name) values ('554','Cloridrato de Clindamicina 300mg - 16 Cápsulas');
insert into generico_grupo(grupo,name) values ('558','Cloridrato de Moxifloxacino 400mg - 7 comprimidos');
insert into generico_grupo(grupo,name) values ('564','Levofloxacino 500mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('565','Levofloxacino 500mg - 7 Comprimidos');
insert into generico_grupo(grupo,name) values ('566','Levofloxacino 500mg - 3 Comprimidos');
insert into generico_grupo(grupo,name) values ('567','Levofloxacino 750mg - 5 Comprimidos');
insert into generico_grupo(grupo,name) values ('569','Norfloxacino 400mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('574','Cetoconazol 200mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('575','Cetoconazol 200mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('576','Cloridrato de Terbinafina 250mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('577','Cloridrato de Terbinafina 250mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('578','Fluconazol 150mg - 1 Comprimido');
insert into generico_grupo(grupo,name) values ('579','Fluconazol 150mg - 2 Comprimidos');
insert into generico_grupo(grupo,name) values ('580','Itraconazol 100mg - 15 Cápsulas');
insert into generico_grupo(grupo,name) values ('581','Itraconazol 100mg - 4 Cápsulas');
insert into generico_grupo(grupo,name) values ('584','Aciclovir 200mg - 25 Comprimidos');
insert into generico_grupo(grupo,name) values ('588','Aciclovir 400mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('590','Cloridrato de Valaciclovir 500mg - 42 comprimidos');
insert into generico_grupo(grupo,name) values ('591','Bimatoprosta Solução Oftálmica 3mg/ml - 3ml');
insert into generico_grupo(grupo,name) values ('593','Bimatoprosta Solução Oftálmica 3mg/ml - 5ml');
insert into generico_grupo(grupo,name) values ('595','Cloridrato de Ciprofloxacino Solução Oftálmica 35% - 5ml');
insert into generico_grupo(grupo,name) values ('597','Cloridrato de Dorzolamida 2% - 5ml Solução Oftálmica');
insert into generico_grupo(grupo,name) values ('598','Latanoprosta 50mcg/ml - 2,5ml');
insert into generico_grupo(grupo,name) values ('599','Maleato Timolol 0,25% Colírio - 5ml');
insert into generico_grupo(grupo,name) values ('600','Maleato de Timolol Colírio 0,5% - 5ml');
insert into generico_grupo(grupo,name) values ('601','Ofloxacino 0,30% Genérico - 5ml');
insert into generico_grupo(grupo,name) values ('603','Tartarato De Brimonidina 0,2% - 5ml Solução Oftálmica');
insert into generico_grupo(grupo,name) values ('605','Travoprosta 0,04mg Solução Oftálmica - 2,5ml');
insert into generico_grupo(grupo,name) values ('606','Cetorolaco Trometamina Solução 5mg/ml - 5ml');
insert into generico_grupo(grupo,name) values ('607','Alendronato Sódico 70mg - 4 Comprimidos');
insert into generico_grupo(grupo,name) values ('608','Alendronato Sódico 70mg - 8 Comprimidos');
insert into generico_grupo(grupo,name) values ('609','Ibandronato de Sódio 150mg - 1 Comprimido');
insert into generico_grupo(grupo,name) values ('610','Risedronato Sódico 35mg - 4 Comprimidos');
insert into generico_grupo(grupo,name) values ('611','Albendazol 400mg - 1 Comprimido');
insert into generico_grupo(grupo,name) values ('612','Albendazol 40mg Suspensão Oral - 10ml');
insert into generico_grupo(grupo,name) values ('613','Benzoilmetronidazol 40mg/ml Suspensão Oral - 120ml');
insert into generico_grupo(grupo,name) values ('614','Metronidazol 250mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('618','Secnidazol 1000mg - 2 Comprimidos');
insert into generico_grupo(grupo,name) values ('619','Secnidazol 1000mg - 4 Comprimidos');
insert into generico_grupo(grupo,name) values ('620','Secnidazol Suspensão em Pó 450mg - 15ml');
insert into generico_grupo(grupo,name) values ('621','Secnidazol Suspensão em Pó 900mg - 30ml');
insert into generico_grupo(grupo,name) values ('638','Dicloridrato de Betaistina 16mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('639','Dicloridrato de Betaistina 24mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('640','Cloridrato de Betaistina 8mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('682','Cloridrato de Nortriptilina 25mg - 30 Cápsulas');
insert into generico_grupo(grupo,name) values ('683','Cloridrato de Nortriptilina 75mg - 30 Cápsulas');
insert into generico_grupo(grupo,name) values ('686','Cloridrato de Paroxetina 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('692','Cloridrato de Sertralina 50mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('693','Cloridrato de Sertralina 50mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('737','Maleato de Midazolam 15mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('750','Oxalato de Escitalopram 15mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('766','Risperidona 1mg - 30 comprimidos');
insert into generico_grupo(grupo,name) values ('767','Risperidona 1mg - 60 comprimidos');
insert into generico_grupo(grupo,name) values ('781','Desogestrel 75mcg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('785','Desogestrel 75mcg - 84 Comprimidos');
insert into generico_grupo(grupo,name) values ('788','Dienogeste 2mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('789','Dienogeste 2mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('798','Levonorgestrel 1,5mg - 1 Comprimido');
insert into generico_grupo(grupo,name) values ('799','Noretisterona 0,35mg - 35 Comprimidos');
insert into generico_grupo(grupo,name) values ('800','Citrato de Sildenafila 100mg - 1 Comprimido');
insert into generico_grupo(grupo,name) values ('801','Citrato de Sildenafila 100mg - 2 Comprimidos');
insert into generico_grupo(grupo,name) values ('802','Citrato de Sildenafila 100mg - 4 Comprimidos');
insert into generico_grupo(grupo,name) values ('803','Citrato de Sildenafila 25mg - 2 Comprimidos');
insert into generico_grupo(grupo,name) values ('804','Citrato de Sildenafila 25mg - 4 Comprimidos');
insert into generico_grupo(grupo,name) values ('805','Citrato de Sildenafila 50mg - 8 Comprimidos');
insert into generico_grupo(grupo,name) values ('806','Citrato de Sildenafila 50mg - 1 Comprimido');
insert into generico_grupo(grupo,name) values ('808','Citrato de Sildenafila 50mg - 2 Comprimidos');
insert into generico_grupo(grupo,name) values ('809','Citrato de Sildenafila 50mg - 4 Comprimidos');
insert into generico_grupo(grupo,name) values ('810','Tadalafila 20mg - 1 Comprimido');
insert into generico_grupo(grupo,name) values ('811','Tadalafila 20mg - 2 Comprimidos');
insert into generico_grupo(grupo,name) values ('812','Tadalafila 20mg - 4 Comprimidos');
insert into generico_grupo(grupo,name) values ('813','Tadalafila 5mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('814','Tadalafila 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('815','Clotrimazol Creme Dermatológico 10mg/g - 35g');
insert into generico_grupo(grupo,name) values ('827','Cloridrato de Oxibutinina Xarope 1mg/ml - 120ml');
insert into generico_grupo(grupo,name) values ('828','Cloridrato de Tansulosina 0,4mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('829','Cloridrato de Tansulosina 0,4mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('830','Cloridrato de Tansulosina 0,4mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('832','Finasterida 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('833','Succinato de Solifecacina 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('834','Succinato de Solifecacina 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('1002','Albendazol 400mg - 3 Comprimidos Mastigáveis');
insert into generico_grupo(grupo,name) values ('1028','Albendazol 400mg - 5 Comprimidos Mastigáveis');
insert into generico_grupo(grupo,name) values ('1032','Bromidrato Fenoterol Gotas 5mg/ml - 20ml');
insert into generico_grupo(grupo,name) values ('1033','Cabergolina 0,5mg - 8 Comprimidos');
insert into generico_grupo(grupo,name) values ('1040','Digoxina Elixir 0,05mg/ml - 60ml');
insert into generico_grupo(grupo,name) values ('1050','Sulfato de Salbutamol 2,0mg/ml -120ml');
insert into generico_grupo(grupo,name) values ('3000','Cabergolina 0,5mg - 2 Comprimidos');
insert into generico_grupo(grupo,name) values ('3002','Digoxina 0,25mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('3004','Dipropionato de Beclometasona 250mcg - 200 Doses');
insert into generico_grupo(grupo,name) values ('3008','Furoato de Mometasona Monoidratado 50mcg - Spray 60 Doses');
insert into generico_grupo(grupo,name) values ('3009','Furoato de Mometasona Monoidratado 50mcg - Spray 120 Doses');
insert into generico_grupo(grupo,name) values ('3010','Gliclazida 60mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('3011','Hemifumarato de Bisoprolol 2,5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3012','Acetato de Hidrocortisona 10mg/g - 20g Creme');
insert into generico_grupo(grupo,name) values ('3014','Ibuprofeno 600mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('3016','Montelucaste de Sódio 10mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('3021','Omeprazol 10mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('3022','Omeprazol 40mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('3025','Cloridrato de Pioglitazona 15mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('3026','Piroxicam 20mg - 10 Cápsulas');
insert into generico_grupo(grupo,name) values ('3029','Fosfato Sódico de Prednisolona 11mg/ml - 20ml');
insert into generico_grupo(grupo,name) values ('3030','Prednisolona 5mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('3031','Prednisolona 40mg - 7 Comprimidos');
insert into generico_grupo(grupo,name) values ('3032','Cloridrato de Propafenona 300mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('3035','Cloridrato de Amiodarona 100mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3036','Pitavastatina Cálcica 2mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3038','Dicloridrato de Manidipino 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3039','Dicloridrato de Hidroxizina 2mg/ml - 120ml');
insert into generico_grupo(grupo,name) values ('3041','Cloridrato de Bromexina Xarope Adulto 1,6mg/ml - 120ml');
insert into generico_grupo(grupo,name) values ('3045','Cloridrato de Nebivolol 5mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('3046','Nitazoxanida 500mg - 6 Comprimidos');
insert into generico_grupo(grupo,name) values ('3047','Cloridrato de Ondansetrona Di-Hidratado 4mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('3048','Cloridrato de Ondansetrona Di-Hidratado 8mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('3049','Cloridrato De Metoclopramida 4mg Gotas - 10ml');
insert into generico_grupo(grupo,name) values ('3051','Hidróxido de Alumínio 61,5mg/ml sabor Hortelã - 240ml');
insert into generico_grupo(grupo,name) values ('3052','Tibolona 2,5 mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3053','Tibolona 2,5mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('3055','Sulfato de Hidroxicloroquina 400mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3056','Colchicina 0,5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3057','Colchicina 0,5mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('3059','Valsartana 80mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3060','Valsartana 320mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3061','Sulfato de Glicosamina 1,5g - 30 Sachês');
insert into generico_grupo(grupo,name) values ('3063','Sulfato de Neomicina 3,5mg/g - 20g Pomada');
insert into generico_grupo(grupo,name) values ('3064','Permetrina 10mg Loção - 60ml');
insert into generico_grupo(grupo,name) values ('3065','Rabeprazol Sódico 10mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('3066','Rabeprazol Sódico 20mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('3070','Varfarina Sódica 5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3071','Alendronato Sódico 70mg - 2 Comprimidos');
insert into generico_grupo(grupo,name) values ('3072','Oxalato de Escitalopram 10mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('3074','Oxalato de Escitalopram 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3075','Oxalato de Escitalopram 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3076','Acetato de Hidrocortisona 10mg/g - 15g Creme');
insert into generico_grupo(grupo,name) values ('3077','Lansoprazol 30mg - 14 Cápsulas');
insert into generico_grupo(grupo,name) values ('3078','Ácido Acetilsalicílico Infantil 100mg - 10 comprimidos');
insert into generico_grupo(grupo,name) values ('3081','Ramipril 2,5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3082','Citrato de Tamoxifeno 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3083','Telmisartana 40mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3084','Cloridrato de Amitriptilina 25mg - 20 comprimidos');
insert into generico_grupo(grupo,name) values ('3085','Glimepirida 4mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3086','Lansoprazol 15mg - 14 Cápsulas');
insert into generico_grupo(grupo,name) values ('3087','Ibuprofeno 200mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('3088','Cloridrato de Amitriptilina 75mg - 30 comprimidos');
insert into generico_grupo(grupo,name) values ('3089','Carvedilol 6,25mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('3092','Cloridrato de Sertralina 100mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3094','Alprazolam 0,25mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3095','Besilato de Anlodipino 5mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('3097','Cloridrato de Fexofenadina 60mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('3098','Cloridrato de Ciclobenzaprina 5mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('3099','Cloridrato de Ciprofloxacino 500mg - 7 Comprimidos');
insert into generico_grupo(grupo,name) values ('3100','Cloridrato de Ciprofloxacino 500mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('3101','Ciprofibrato 100mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('3103','Dienogeste 2mg - 84 Comprimidos');
insert into generico_grupo(grupo,name) values ('3105','Cloridrato de Clomipramina 75mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('3106','Dicloridrato de Betaistina 24mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3107','Cloridrato de Moxifloxacino 400mg - 5 comprimidos');
insert into generico_grupo(grupo,name) values ('3110','Cloridrato de Sertralina 50mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('3111','Alprazolam 0,25mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('3112','Alprazolam 0,5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('3113','Oxalato de Escitalopram 20mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('3114','Paracetamol 750mg - 12 Comprimidos');
insert into generico_grupo(grupo,name) values ('3116','Cloridrato de Tramadol 50mg - 50 Cápsulas');
insert into generico_grupo(grupo,name) values ('4001','Acebrofilina 25mg/5ml Xarope Adulto - 120ml');
insert into generico_grupo(grupo,name) values ('4002','Aceclofenaco 100mg - 24 Comprimidos');
insert into generico_grupo(grupo,name) values ('4003','Aceclofenaco Creme 15mg - 30g');
insert into generico_grupo(grupo,name) values ('4006','Fosfato Sódico de Prednisolona Solução 1mg - 100ml');
insert into generico_grupo(grupo,name) values ('4008','Acetato de Prednisolona Colírio 1% - 5ml');
insert into generico_grupo(grupo,name) values ('4010','Acetilcisteína Intramuscular 100mg - 5x3ml');
insert into generico_grupo(grupo,name) values ('4011','Acetilcisteína Xarope 20mg/ml - 100ml');
insert into generico_grupo(grupo,name) values ('4012','Aciclovir 200mg - 50 Comprimidos');
insert into generico_grupo(grupo,name) values ('4014','Ácido Acetilsalicílico 300mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('4015','Ácido Mefenâmico 500mg - 24 Comprimidos');
insert into generico_grupo(grupo,name) values ('4020','Alopurinol 100mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('4029','Alprazolam 2mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('4030','Alprazolam 1mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('4041','Cloridrato de Amiodarona 200mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('4042','Cloridrato de Amiodarona 200mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('4043','Cloridrato de Amiodarona 100mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('4046','Cloridrato de Amitriptilina 25mg - 30 comprimidos');
insert into generico_grupo(grupo,name) values ('4070','Valsartana 160mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('4071','Valsartana 160mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('4072','Valsartana 40mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('4082','Atenolol 100mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('4090','Atorvastatina Cálcica 10mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('4091','Atorvastatina Cálcica 20mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('4095','Baclofeno 10mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('4097','Benzoilmetronidazol 40mg/ml Suspensão Oral - 100ml');
insert into generico_grupo(grupo,name) values ('4098','Betaistina 24mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('5000','Betametasona 0,5mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('5001','Betametasona Elixir 0,5mg/5ml - 120ml');
insert into generico_grupo(grupo,name) values ('5002','Betametasona 2mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('5007','Bissulfato de Clopidogrel 75mg -14 Comprimidos');
insert into generico_grupo(grupo,name) values ('5009','Candesartana Cilexetila 16mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('5010','Captopril 50mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('5011','Carvedilol 25mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('5015','Cloridrato de Ciprofloxacino 250mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('5016','Ciprofloxacino 500mg - 7 Comprimidos');
insert into generico_grupo(grupo,name) values ('5017','Cloridrato de Ciprofloxacino 250mg - 6 Comprimidos');
insert into generico_grupo(grupo,name) values ('5018','Cloridrato de Ciprofloxacino 250mg - 7 Comprimidos');
insert into generico_grupo(grupo,name) values ('5021','Cloridrato de Ambroxol 7,5mg Solução Oral - 50ml');
insert into generico_grupo(grupo,name) values ('5022','Cloridrato de Clobutinol Xarope 4mg/ml - 120ml');
insert into generico_grupo(grupo,name) values ('5023','Cloridrato de Betaxolol Solução Oftálmica 5mg/ml - 5ml');
insert into generico_grupo(grupo,name) values ('5026','Cloridrato de Bupropiona 150mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('5027','Cloridrato de Bupropiona 150mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('5029','Cloridrato de Clomipramina 25mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('5031','Cloridrato de Doxiciclina 100mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('5033','Cloridrato de Duloxetina 30mg - 30 Cápsulas');
insert into generico_grupo(grupo,name) values ('5034','Cloridrato de Duloxetina 60mg - 30 cápsulas');
insert into generico_grupo(grupo,name) values ('5036','Cloridrato de Naratriptana 2,5mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('5037','Cloridrato de Pioglitazona 30mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('5038','Cloridrato de Pioglitazona 45mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('5039','Cloridrato de Propranolol 80mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('5040','Cloridrato de Valaciclovir 500mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('5041','Cloridrato de Verapamil 240mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('5044','Dexametasona Elixir 0,1mg/ml - 120ml');
insert into generico_grupo(grupo,name) values ('5045','Diazepan 5mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('5047','Dicloridrato de Cetirizina 1mg/ml Solução Oral - 120ml');
insert into generico_grupo(grupo,name) values ('5060','Tinidazol 500mg - 4 Comprimidos');
insert into generico_grupo(grupo,name) values ('5061','Fosfato de Oseltamivir 30mg - 10 Cápsulas');
insert into generico_grupo(grupo,name) values ('5062','Fosfato de Oseltamivir 45mg - 10 Cápsulas');
insert into generico_grupo(grupo,name) values ('5063','Fosfato de Oseltamivir 75mg - 10 Cápsulas');
insert into generico_grupo(grupo,name) values ('5080','Fumarato de Cetotifeno Xarope 0,2mg/ml - 120ml');
insert into generico_grupo(grupo,name) values ('5081','Gliclazida 60mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('5083','Metronidazol Gel Vaginal 500mg/5g - 50g');
insert into generico_grupo(grupo,name) values ('5086','Tobramicina 3mg/ml Genérico Germed 5ml Solução Oftálmica');
insert into generico_grupo(grupo,name) values ('7000','Pantoprazol Sódico Sesqui-Hidratado 20mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('7001','Pantoprazol Sódico Sesqui-Hidratado 40mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('7006','Cloridrato de Clobutinol Solução Oral 60mg/ml - 20ml');
insert into generico_grupo(grupo,name) values ('7007','Diclofenaco Sódico 25mg/ml - 5 Ampolas com 3ml');
insert into generico_grupo(grupo,name) values ('7008','Cloridrato de Hidroxizina 2mg/ml Xarope - 120ml');
insert into generico_grupo(grupo,name) values ('7009','Cloridrato de Pioglitazona 15mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('7010','Risedronato Sódico 150mg - 1 Comprimido');
insert into generico_grupo(grupo,name) values ('7011','Diclofenaco de Dietilamônio 10mg/g Creme - 60g');
insert into generico_grupo(grupo,name) values ('7012','Naproxeno Sódico 550mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('7013','Prednisona 20mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('7014','Prednisolona 5mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11000','Acetilcisteina Granulado 20Mg - 16 Envelopes');
insert into generico_grupo(grupo,name) values ('11001','Aciclovir 200mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11002','Aciclovir 400mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('11003','Aciclovir 400mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('11004','Ácido Acetilsalicílico 500mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('11005','Alprazolam 0,5mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11006','Alprazolam 1mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11007','Alprazolam 2mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11008','Amoxicilina 50mg/ml - Suspensao Oral Com 150ml');
insert into generico_grupo(grupo,name) values ('11009','Amoxicilina 80mg/ml - Suspensao Oral Com 150ml');
insert into generico_grupo(grupo,name) values ('11010','Amoxicilina 500mg - 15 Capsulas');
insert into generico_grupo(grupo,name) values ('11011','Amoxicilina 500mg - 21 Capsulas');
insert into generico_grupo(grupo,name) values ('11012','Amoxicilina 500mg - 30 Capsulas');
insert into generico_grupo(grupo,name) values ('11014','Amoxicilina 875mg - 14 Capsulas');
insert into generico_grupo(grupo,name) values ('11015','Amoxicilina Tri-Hidratada 400mg/5ml - 100ml');
insert into generico_grupo(grupo,name) values ('11016','Amoxicilina Suspensao 100mg/ml - 150ml');
insert into generico_grupo(grupo,name) values ('11017','Amoxicilina Clavulanato De Potassio 500/125mg - 12 Comprimidos');
insert into generico_grupo(grupo,name) values ('11018','Amoxicilina Suspensao 125mg/5ml - 150ml');
insert into generico_grupo(grupo,name) values ('11020','Amoxicilina Suspensao 250mg - 60ml');
insert into generico_grupo(grupo,name) values ('11021','Amoxicilina Tri-Hidratada 250mg/5ml - 150ml');
insert into generico_grupo(grupo,name) values ('11022','Amoxicilina Tri-Hidratada 500mg - 21 Capsulas');
insert into generico_grupo(grupo,name) values ('11023','Amoxicilina Tri-Hidratada 500mg - 30 Capsulas');
insert into generico_grupo(grupo,name) values ('11024','Amoxicilina Tri-Hidratada 500mg - 15 Capsulas');
insert into generico_grupo(grupo,name) values ('11026','Amoxicilina Tri-Hidratada 875mg - 20 Capsulas');
insert into generico_grupo(grupo,name) values ('11027','Ampicilina Suspensao 250mg/5ml - 60ml');
insert into generico_grupo(grupo,name) values ('11028','Ampicilina Suspensao 250mg/5ml - 150ml');
insert into generico_grupo(grupo,name) values ('11029','Ampicilina 500mg - 24 Comprimidos');
insert into generico_grupo(grupo,name) values ('11030','Ampicilina 500mg - 6 Comprimidos');
insert into generico_grupo(grupo,name) values ('11031','Ampicilina 500mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('11032','Ampicilina Tri-Hidratada 500mg - 12 Comprimidos');
insert into generico_grupo(grupo,name) values ('11033','Aripiprazol 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11034','Aripiprazol 15mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11035','Aripiprazol 30mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11036','Axetilcefuroxima Suspensao 250mg - 50ml');
insert into generico_grupo(grupo,name) values ('11037','Axetilcefuroxima 250mg - 50ml');
insert into generico_grupo(grupo,name) values ('11038','Axetilcefuroxima 500mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('11039','Azitromicina 500mg - 3 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11040','Azitromicina 1G - 1 Comprimido');
insert into generico_grupo(grupo,name) values ('11041','Azitromicina Di-Hidratada 1500mg - Suspensao Oral 37,5ml');
insert into generico_grupo(grupo,name) values ('11042','Azitromicina Di-Hidratada 500mg - 3 Comprimidos');
insert into generico_grupo(grupo,name) values ('11043','Azitromicina 600mg - Suspensao Oral 15Ml');
insert into generico_grupo(grupo,name) values ('11044','Azitromicina 900mg - Suspensao Oral 15Ml');
insert into generico_grupo(grupo,name) values ('11045','Azitromicina Di-Hidratada 900mg - Suspensao Oral Com 22,5ml');
insert into generico_grupo(grupo,name) values ('11046','Azitromicina Di-Hidratada 500mg - 2 Comprimidos');
insert into generico_grupo(grupo,name) values ('11047','Azitromicina 500Mg 5 - Comprimidos ');
insert into generico_grupo(grupo,name) values ('11048','Azitromicina Di-Hidratada 900mg - Suspensao Oral Com 12ml');
insert into generico_grupo(grupo,name) values ('11049','Benzoilmetronidazol 40mg/ml Suspensão Oral - 80ml');
insert into generico_grupo(grupo,name) values ('11051','Bicalutamida 50mg  - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('11052','Bromazepam 2,5mg/Ml - 20ml');
insert into generico_grupo(grupo,name) values ('11053','Bromazepam 3mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11054','Bromazepam 3mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11055','Bromazepam 6mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11056','Bromazepam 6mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11057','Brometo N-Butilescopolamina Gotas 10mg/ml - 20ml ');
insert into generico_grupo(grupo,name) values ('11058','Bromidrato De Citalopram 20mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11059','Bromidrato De Citalopram 20mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('11060','Bromidrato De Citalopram 20mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('11061','Bromidrato De Galantamina 16mg - 30 Capsulas');
insert into generico_grupo(grupo,name) values ('11062','Bromidrato De Galantamina 24mg - 30 Capsulas');
insert into generico_grupo(grupo,name) values ('11063','Bromidrato De Galantamina 8mg - 30 Capsulas');
insert into generico_grupo(grupo,name) values ('11064','Bromoprida 1mg - 120ml');
insert into generico_grupo(grupo,name) values ('11065','Butilbrometo De Escopolamina 10mg/ml Gotas - 20ml');
insert into generico_grupo(grupo,name) values ('11066','Carbamazepina 200mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11067','Carbamazepina 200mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11068','Carbamazepina 400mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11069','Carbamazepina 400mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11070','Carbamazepina Suspensao Oral - 100ml');
insert into generico_grupo(grupo,name) values ('11071','Carbonato De Litio 300mg - 50 Comprimidos');
insert into generico_grupo(grupo,name) values ('11072','Carvedilol 3,125mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('11073','Cefaclor 250mg/5ml Suspensao - 80ml');
insert into generico_grupo(grupo,name) values ('11074','Cefaclor 375mg/5ml Suspensao - 80ml');
insert into generico_grupo(grupo,name) values ('11075','Cefaclor 500mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('11076','Cefalexina 100mg/Ml Suspensao - 100Ml');
insert into generico_grupo(grupo,name) values ('11078','Ceftriaxona Sodica Im 1G Po Para Solucao Injetavel Com 5 Ampolas De 3,5Ml');
insert into generico_grupo(grupo,name) values ('11079','Ceftriaxona Sodica 500mg Po Para Solucao Injetavel Com 1 Ampola De 2Ml');
insert into generico_grupo(grupo,name) values ('11080','Ceftriaxona Sodica Intramuscular 0,5Mg - 5Ml');
insert into generico_grupo(grupo,name) values ('11081','Ceftriaxona Sodica Intramuscular 1G Generico - 5Ml');
insert into generico_grupo(grupo,name) values ('11082','Celecoxibe 100mg Generico - 20 Capsulas');
insert into generico_grupo(grupo,name) values ('11084','Clonazepam 0,5mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11085','Clonazepam 0,5mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('11086','Clonazepam 2mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11087','Clonazepam 2mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('11088','Clonazepam 2mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11089','Clonazepam Solucao Oral 25mg/Ml - 20ml');
insert into generico_grupo(grupo,name) values ('11090','Cloridrato Azelastina 1mg/ml - Solucao 10ml');
insert into generico_grupo(grupo,name) values ('11091','Cloridrato de Amitriptilina 75mg - 20 comprimidos');
insert into generico_grupo(grupo,name) values ('11094','Cloridrato de Clomipramina 10mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11095','Donepezil 10Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11096','Donepezila 5Mg -30 Comprimidos Revestidos');
insert into generico_grupo(grupo,name) values ('11097','Cloridrato De Fluoxetina 10mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11098','Fluoxetina 10Mg - 28 Capsulas');
insert into generico_grupo(grupo,name) values ('11099','Fluoxetina 20Mg - 30 Capsulas');
insert into generico_grupo(grupo,name) values ('11100','Fluoxetina 20Mg - 28 Capsulas');
insert into generico_grupo(grupo,name) values ('11101','Cloridrato De Fluoxetina 20mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('11102','Cloridrato De Lidocaina 2% 20mg/G - 1 Bisnaga 30G');
insert into generico_grupo(grupo,name) values ('11103','Cloridrato De Lincomicina 600mg/ml - 2ml');
insert into generico_grupo(grupo,name) values ('11104','Memantina 10Mg - 60 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11105','Memantina 10Mg - 30 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11106','Cloridrato De Metilfenidato 10mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11107','Cloridrato De Metilfenidato 10mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('11108','Cloridrato de Nortriptilina 50mg - 20 Cápsulas');
insert into generico_grupo(grupo,name) values ('11109','Cloridrato de Nortriptilina 50mg - 30 Cápsulas');
insert into generico_grupo(grupo,name) values ('11110','Cloridrato de Nortriptilina 75mg - 20 Cápsulas');
insert into generico_grupo(grupo,name) values ('11111','Sertralina 100Mg - 14 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11112','Cloridrato de Sertralina 100mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11113','Cloridrato de Terbinafina 250mg - 7 Comprimidos');
insert into generico_grupo(grupo,name) values ('11114','Trazodona 100Mg - 30 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11115','Trazodona 50Mg - 60 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11116','Cloridrato De Venlafaxina 150mg - 15 Capsulas');
insert into generico_grupo(grupo,name) values ('11117','Cloridrato De Venlafaxina 37,5mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('11118','Cloridrato De Venlafaxina 37,5mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('11119','Cloridrato De Venlafaxina 37,5mg - 7 Comprimidos');
insert into generico_grupo(grupo,name) values ('11120','Cloridrato De Venlafaxina 50mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11121','Cloridrato De Venlafaxina 75mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('11122','Cloridrato Venlafaxina 75Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11123','Cloridrato Fenoxazolina Solucao Nasal Adulto 10Mg - 10ml');
insert into generico_grupo(grupo,name) values ('11124','Cloridrato Fenoxazolina Solucao Nasal Infantil 5mg - 10Ml');
insert into generico_grupo(grupo,name) values ('11128','Cloridrato Minociclina 100Mg - 9 Comprimidos');
insert into generico_grupo(grupo,name) values ('11129','Cloridrato Nortriptilina 10Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11130','Cloridrato Oximetazolina Adulto 5Mg/Ml - 10Ml');
insert into generico_grupo(grupo,name) values ('11131','Cloridrato Prometazina 25Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11132','Cloridrato Ranitidina 300Mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('11133','Cloridrato Tetraciclina 500Mg - 12 Capsulas');
insert into generico_grupo(grupo,name) values ('11134','Cloridrato Tramadol 100Mg - 15Ml Solucao Oral');
insert into generico_grupo(grupo,name) values ('11135','Clotrimazol Creme Dermatológico 10mg/g - 50g');
insert into generico_grupo(grupo,name) values ('11136','Clotrimazol Creme Dermatológico 20mg/g - 20g');
insert into generico_grupo(grupo,name) values ('11137','Cloxazolam 1Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11138','Cloxazolam 1Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11139','Cloxazolam 2Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11140','Cloxazolam 2Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11141','Desonida Locao Dermatologica 0,5Mg/G - 30G');
insert into generico_grupo(grupo,name) values ('11142','Desonida Locao Topica 0,5Mg - 60G');
insert into generico_grupo(grupo,name) values ('11143','Succinato De Desvenlafaxina 100Mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('11144','Desvenlafaxina 50Mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('11145','Diazepam 10Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11146','Diazepam 10Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11147','Diazepam 5Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11148','Diclofenaco Colestiramina 70Mg - 10 Capsulas');
insert into generico_grupo(grupo,name) values ('11149','Dicloridrato De Cetirizina 10Mg - 6 Comprimidos');
insert into generico_grupo(grupo,name) values ('11150','Dicloridrato De Pramipexol 0,125Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11151','Dicloridrato De Pramipexol 0,25Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11152','Dicloridrato De Pramipexol 1Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11153','Digoxina 0,25mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11154','Digoxina 0,25mg - 25 Comprimidos');
insert into generico_grupo(grupo,name) values ('11155','Dipirona Monoidratada 500Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11156','Dipirona Sódica 1g - 4 comprimidos');
insert into generico_grupo(grupo,name) values ('11157','Dipirona Sódica 500mg - 4 Comprimidos');
insert into generico_grupo(grupo,name) values ('11158','Divalproato De Sodio 250Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11159','Divalproato De Sodio 250Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11160','Divalproato De Sodio 500Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11161','Divalproato De Sodio 500Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11162','Dropropizina Xarope 1,5Mg/Ml Generico Medley 120Ml');
insert into generico_grupo(grupo,name) values ('11163','Estolato De Eritromicina 50Mg/Ml - 105Ml');
insert into generico_grupo(grupo,name) values ('11164','Estolato Eritromicina 500Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11165','Estolato De Eritromicina 50Mg/Ml - 80Ml');
insert into generico_grupo(grupo,name) values ('11166','Fenobarbital 100Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11167','Fenobarbital 100Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11168','Fenobarbital Solucao Oral 40Mg/Ml - 20Ml');
insert into generico_grupo(grupo,name) values ('11169','Fosfato Clindamicina Gel Topico 100Mg/G Generico Ems 45G');
insert into generico_grupo(grupo,name) values ('11170','Fumarato Cetotifeno 1Mg/Ml Xarope - 120Ml');
insert into generico_grupo(grupo,name) values ('11171','Fumarato De Cetotifeno Xarope 1Mg/5Ml - 100Ml');
insert into generico_grupo(grupo,name) values ('11172','Quetiapina 100Mg - 30 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11173','Quetiapina 200Mg - 30 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11174','Fumarato De Quetiapina 25Mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('11175','Quetiapina 25Mg - 30 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11176','Fumarato Quetiapina 100Mg - 28 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11177','Fumarato Quetiapina 200Mg - 28 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11178','Fumarato Quetiapina 25Mg - 28 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11180','Hemifumarato De Quetiapina 50Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11181','Gabapentina 300Mg - 30 Capsulas ');
insert into generico_grupo(grupo,name) values ('11182','Gabapentina 400Mg - 30 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11183','Gabapentina 600Mg - 27 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11184','Galantamina 16Mg Generico - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('11185','Galantamina 8Mg Generico - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('11186','Guaifenesina Xarope 13,33Mg/Ml - 120Ml');
insert into generico_grupo(grupo,name) values ('11188','Zolpidem 10Mg - 30 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11189','Zolpidem 10Mg - 20 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11190','Hemitartarato De Zolpidem 6,25Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('11191','Zolpidem 10Mg - 10 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11192','Zolpidem 5Mg - 30 Comprimidos ');
insert into generico_grupo(grupo,name) values ('11195','Ibuprofeno 600mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('11196','Irbesartana 150mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('11197','Irbesartana 300mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12000','Cloridrato Fluoxetina - 20ml');
insert into generico_grupo(grupo,name) values ('12001','Cloridrato Venlafaxina 150Mg - 30 Capsulas');
insert into generico_grupo(grupo,name) values ('12002','Cloridrato Venlafaxina 150Mg - 14 Capsulas');
insert into generico_grupo(grupo,name) values ('12003','Cloridrato Venlafaxina 150Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12004','Cloridrato Venlafaxina 37,5Mg - 30 Capsulas');
insert into generico_grupo(grupo,name) values ('12005','Cloridrato Venlafaxina 75Mg - 14 Capsulas');
insert into generico_grupo(grupo,name) values ('12006','Cloridrato Venlafaxina 75Mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('12007','Cloridrato Terbinafina Solucao Topica 1% - 30Ml');
insert into generico_grupo(grupo,name) values ('12200','Succinato De Desvenlafaxina 100Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12201','Succinato De Desvenlafaxina 100Mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('12202','Succinato De Desvenlafaxina 50Mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('12203','Succinato De Desvenlafaxina 50Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12204','Lamotrigina 25Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12205','Lamotrigina 50Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12206','Lansoprazol 30mg - 7 Cápsulas');
insert into generico_grupo(grupo,name) values ('12207','Lorazepam 1Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('12208','Lorazepam 2Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12209','Lorazepam 2Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('12210','Lovastatina 40Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12211','Maleato de Midazolam 15mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('12212','Maleato de Midazolam 7,5mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('12213','Mebendazol 100Mg - 6 Comprimidos');
insert into generico_grupo(grupo,name) values ('12214','Mebendazol Suspensao 100Mg/5Ml - 30Ml');
insert into generico_grupo(grupo,name) values ('12215','Mesilato De Codergocrina 1Mg/Ml - Solucao Oral Com 30Ml');
insert into generico_grupo(grupo,name) values ('12216','Mesilato De Codergocrina 4,5Mg - 15Ml');
insert into generico_grupo(grupo,name) values ('12217','Metoclopramida Sf - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('12218','Metronidazol 400Mg - 24 Comprimidos');
insert into generico_grupo(grupo,name) values ('12219','Minociclina 100Mg  - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12220','Mirtazapina 15Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12221','Mirtazapina Odt 15Mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('12222','Mirtazapina 30Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12223','Mirtazapina 30Mg - 14 Comprimidos ');
insert into generico_grupo(grupo,name) values ('12224','Mirtazapina Odt 30Mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('12225','Mirtazapina Odt 45Mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('12228','Naproxeno 250mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('12229','Nistatina 25.000Ui/G - 60G');
insert into generico_grupo(grupo,name) values ('12230','Nistatina Creme Vaginal - 60G');
insert into generico_grupo(grupo,name) values ('12231','Nitrato De Miconazol Creme Vaginal - 14 Aplicadores');
insert into generico_grupo(grupo,name) values ('12232','Nitrato Fenticonazol Creme 40Gr Generico - 7 Aplicadores');
insert into generico_grupo(grupo,name) values ('12233','Norfloxacino 400Mg - 6 Comprimidos');
insert into generico_grupo(grupo,name) values ('12234','Onaz 10Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12235','Olanzapina 10Mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('12236','Onaz 2,5Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12237','Olanzapina 25Mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('12238','Onaz 5Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12239','Oxalato de Escitalopram 10mg - 15 Comprimidos');
insert into generico_grupo(grupo,name) values ('12241','Oxalato de Escitalopram 10mg - 14 Comprimidos');
insert into generico_grupo(grupo,name) values ('12242','Oxalato de Escitalopram 10mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('12245','Oxalato De Escitalopram 20Mg/Ml - 15Ml');
insert into generico_grupo(grupo,name) values ('12246','Oxcarbazepina 300Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12247','Oxcarbazepina 300Mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('12248','Oxcarbazepina 300Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('12249','Oxcarbazepina 600Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12250','Oxcarbazepina 600Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('12251','Oxcarbazepina 600Mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('12252','Oxcarbazepina 60Mg/Ml - 100Ml');
insert into generico_grupo(grupo,name) values ('12253','Pantoprazol 40mg - 7 Comprimidos');
insert into generico_grupo(grupo,name) values ('12254','Paracetamol 100Mg/Ml - 15Ml Gotas');
insert into generico_grupo(grupo,name) values ('12255','Paracetamol 160Mg/Ml - 60Ml Suspensao');
insert into generico_grupo(grupo,name) values ('12256','Paracetamol Suspensao 32Mg/Ml - 60Ml');
insert into generico_grupo(grupo,name) values ('12257','Paracetamol 500Mg - 4 Comprimidos');
insert into generico_grupo(grupo,name) values ('12258','Paracetamol 500Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('12259','Paracetamol 500Mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('12260','Paracetamol Solucao Oral Po 500Mg - Sachê 5G');
insert into generico_grupo(grupo,name) values ('12261','Prednisolona 40mg - 10 Comprimidos');
insert into generico_grupo(grupo,name) values ('12262','Pregabalina 150Mg - 30 Capsulas');
insert into generico_grupo(grupo,name) values ('12263','Pregabalina 150Mg - 28 Capsulas');
insert into generico_grupo(grupo,name) values ('12264','Pregabalina 75Mg - 30 Capsulas');
insert into generico_grupo(grupo,name) values ('12265','Pregabalina 75Mg - 28 Capsulas');
insert into generico_grupo(grupo,name) values ('12269','Propionato De Clobetasol Solucao Capilar - 50Gr ');
insert into generico_grupo(grupo,name) values ('12271','Risperidona 1Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('12272','Risperidona 2Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12273','Risperidona 2Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('12274','Risperidona 3Mg - 20 Comprimidos');
insert into generico_grupo(grupo,name) values ('12275','Risperidona 3Mg - 30 Comprimidos');
insert into generico_grupo(grupo,name) values ('12276','Risperidona Solucao Oral 1Mg/Ml - 30Ml');
insert into generico_grupo(grupo,name) values ('12277','Sertralina 25Mg - 30 Comprimidos ');
insert into generico_grupo(grupo,name) values ('12278','Simeticona 125mg - 3 Cápsulas');
insert into generico_grupo(grupo,name) values ('12279','Simeticona 40mg - 4 Comprimidos');
insert into generico_grupo(grupo,name) values ('12280','Sinvastatina 20mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('12281','Sinvastatina 80Mg -10 Comprimidos');
insert into generico_grupo(grupo,name) values ('12282','Sulfadiazina Prata 10Mg/G - 30G');
insert into generico_grupo(grupo,name) values ('12283','Sulfato De Salbutamol 2Mg/5Ml - Xarope 120Ml');
insert into generico_grupo(grupo,name) values ('12284','Sulfato Terbutalina Xarope 0,3Mg/Ml - 100Ml');
insert into generico_grupo(grupo,name) values ('12286','Tinidazol 500mg - 8 Comprimidos');
insert into generico_grupo(grupo,name) values ('12287','Tioconazol Creme Dermatologico 30Mg - 30G');
insert into generico_grupo(grupo,name) values ('12288','Topiramato 100Mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('12289','Topiramato 25Mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('12290','Topiramato 50Mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('12291','Valsartana 320mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('12292','Valsartana 320mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('12293','Valsartana 80mg - 60 Comprimidos');
insert into generico_grupo(grupo,name) values ('12294','Valsartana 80mg - 28 Comprimidos');
insert into generico_grupo(grupo,name) values ('12400','Itraconazol 100mg - 10 Cápsulas');
insert into generico_grupo(grupo,name) values ('14000','Levofloxacino Hemi-Hidratado 500Mg - 7 Comprimidos');
insert into generico_grupo(grupo,name) values ('14001','Cloridrato Fluoxetina 20mg- 20Ml');
